// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proxy/mtproto/config.proto

package mtproto

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Brocade uses the user's UUID as the 16-byte MTProxy secret. Keeping the
	// canonical UUID string on the control channel makes grant reconciliation
	// identical to VLESS, AnyTLS and Hysteria 2; the server decodes it only at
	// the protocol boundary.
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_mtproto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mtproto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_mtproto_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_mtproto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mtproto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_mtproto_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proxy_mtproto_config_proto protoreflect.FileDescriptor

const file_proxy_mtproto_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/mtproto/config.proto\x12\x12xray.proxy.mtproto\x1a\x1acommon/protocol/user.proto\"!\n" +
	"\aAccount\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"@\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05usersBX\n" +
	"\x16com.xray.proxy.mtprotoP\x01Z'github.com/xtls/xray-core/proxy/mtproto\xaa\x02\x12Xray.Proxy.Mtprotob\x06proto3"

var (
	file_proxy_mtproto_config_proto_rawDescOnce sync.Once
	file_proxy_mtproto_config_proto_rawDescData []byte
)

func file_proxy_mtproto_config_proto_rawDescGZIP() []byte {
	file_proxy_mtproto_config_proto_rawDescOnce.Do(func() {
		file_proxy_mtproto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_mtproto_config_proto_rawDesc), len(file_proxy_mtproto_config_proto_rawDesc)))
	})
	return file_proxy_mtproto_config_proto_rawDescData
}

var file_proxy_mtproto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_mtproto_config_proto_goTypes = []any{
	(*Account)(nil),       // 0: xray.proxy.mtproto.Account
	(*ServerConfig)(nil),  // 1: xray.proxy.mtproto.ServerConfig
	(*protocol.User)(nil), // 2: xray.common.protocol.User
}
var file_proxy_mtproto_config_proto_depIdxs = []int32{
	2, // 0: xray.proxy.mtproto.ServerConfig.users:type_name -> xray.common.protocol.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_mtproto_config_proto_init() }
func file_proxy_mtproto_config_proto_init() {
	if File_proxy_mtproto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_mtproto_config_proto_rawDesc), len(file_proxy_mtproto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_mtproto_config_proto_goTypes,
		DependencyIndexes: file_proxy_mtproto_config_proto_depIdxs,
		MessageInfos:      file_proxy_mtproto_config_proto_msgTypes,
	}.Build()
	File_proxy_mtproto_config_proto = out.File
	file_proxy_mtproto_config_proto_goTypes = nil
	file_proxy_mtproto_config_proto_depIdxs = nil
}
