-- Xray binaries are operational software, not model artifacts. A release therefore has no model
-- revision, but it still needs immutable identity, an auditable operator trail, and per-machine
-- progress because replacing a serving Xray interrupts connections. `artifacts` freezes the
-- architecture-to-sha mapping carried by the Console that created this release; a later Console
-- can never silently substitute the bytes under an existing release id.
CREATE TABLE xray_releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    idempotency_key TEXT NOT NULL,
    build_id TEXT NOT NULL,
    version TEXT NOT NULL,
    artifacts JSONB NOT NULL,
    status TEXT DEFAULT 'running' NOT NULL,
    active BOOLEAN DEFAULT true NOT NULL,
    confirmed_wave INTEGER DEFAULT 1 NOT NULL,
    batch_size INTEGER DEFAULT 10 NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    created_by TEXT NOT NULL,
    halted_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    CONSTRAINT xray_releases_pkey PRIMARY KEY (id),
    CONSTRAINT xray_releases_idempotency_key_key UNIQUE (idempotency_key),
    CONSTRAINT xray_releases_idempotency_key_length CHECK ((length(idempotency_key) BETWEEN 1 AND 200)),
    CONSTRAINT xray_releases_build_id_shape CHECK ((build_id ~ '^[0-9a-f]{64}$')),
    CONSTRAINT xray_releases_version_shape CHECK (((length(version) BETWEEN 1 AND 128))),
    CONSTRAINT xray_releases_artifacts_shape CHECK (((jsonb_typeof(artifacts) = 'object') AND (artifacts <> '{}'::jsonb))),
    CONSTRAINT xray_releases_note_length CHECK (((note IS NULL) OR (length(note) <= 2000))),
    CONSTRAINT xray_releases_status_known CHECK ((status IN ('running', 'halted', 'succeeded', 'canceled'))),
    CONSTRAINT xray_releases_active_status_consistent CHECK (((active AND (status IN ('running', 'halted'))) OR ((NOT active) AND (status IN ('succeeded', 'canceled'))))),
    CONSTRAINT xray_releases_confirmed_wave_check CHECK ((confirmed_wave >= 1)),
    CONSTRAINT xray_releases_batch_size_check CHECK ((batch_size BETWEEN 1 AND 500)),
    CONSTRAINT xray_releases_created_by_fkey FOREIGN KEY (created_by) REFERENCES admin_operators(id) ON DELETE RESTRICT
);

CREATE TABLE xray_release_targets (
    release_id BIGINT NOT NULL,
    node_id TEXT NOT NULL,
    wave INTEGER NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL,
    attempt INTEGER DEFAULT 1 NOT NULL,
    before_sha256 TEXT NOT NULL,
    desired_sha256 TEXT,
    arch TEXT,
    error TEXT,
    reported_performed_update BOOLEAN,
    reported_xray_enabled BOOLEAN,
    reported_installed_sha256 TEXT,
    reported_running_sha256 TEXT,
    dispatched_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    CONSTRAINT xray_release_targets_pkey PRIMARY KEY (release_id, node_id),
    CONSTRAINT xray_release_targets_release_fkey FOREIGN KEY (release_id) REFERENCES xray_releases(id) ON DELETE CASCADE,
    -- Keep the textual machine identity after a terminal node is permanently removed. Binary
    -- releases are an immutable audit ledger, so deleting their targets would falsify history.
    CONSTRAINT xray_release_targets_wave_check CHECK ((wave >= 1)),
    CONSTRAINT xray_release_targets_attempt_check CHECK ((attempt >= 1)),
    CONSTRAINT xray_release_targets_before_sha_shape CHECK ((before_sha256 ~ '^[0-9a-f]{64}$')),
    CONSTRAINT xray_release_targets_desired_sha_shape CHECK (((desired_sha256 IS NULL) OR (desired_sha256 ~ '^[0-9a-f]{64}$'))),
    CONSTRAINT xray_release_targets_arch_shape CHECK (((arch IS NULL) OR ((length(arch) BETWEEN 1 AND 32) AND (arch ~ '^[A-Za-z0-9_-]+$')))),
    CONSTRAINT xray_release_targets_error_length CHECK (((error IS NULL) OR (length(error) <= 4000))),
    CONSTRAINT xray_release_targets_reported_installed_shape CHECK (((reported_installed_sha256 IS NULL) OR (reported_installed_sha256 ~ '^[0-9a-f]{64}$'))),
    CONSTRAINT xray_release_targets_reported_running_shape CHECK (((reported_running_sha256 IS NULL) OR (reported_running_sha256 ~ '^[0-9a-f]{64}$'))),
    CONSTRAINT xray_release_targets_status_known CHECK ((status IN ('pending', 'dispatched', 'succeeded', 'unverified', 'failed-recovered', 'failed-dirty', 'unsupported', 'canceled')))
);

-- Status columns answer the current operational question; events retain who moved the rollout and
-- what each Agent reported, so confirmations, retries, cancellation and failures remain auditable.
CREATE TABLE xray_release_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    release_id BIGINT NOT NULL,
    kind TEXT NOT NULL,
    node_id TEXT,
    wave INTEGER,
    actor TEXT,
    detail JSONB DEFAULT '{}'::jsonb NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    CONSTRAINT xray_release_events_pkey PRIMARY KEY (id),
    CONSTRAINT xray_release_events_release_fkey FOREIGN KEY (release_id) REFERENCES xray_releases(id) ON DELETE CASCADE,
    -- `node_id` is an audit snapshot, not a live ownership edge; see the target table above.
    CONSTRAINT xray_release_events_actor_fkey FOREIGN KEY (actor) REFERENCES admin_operators(id) ON DELETE RESTRICT,
    CONSTRAINT xray_release_events_wave_check CHECK (((wave IS NULL) OR (wave >= 1))),
    CONSTRAINT xray_release_events_detail_shape CHECK ((jsonb_typeof(detail) = 'object'))
);
CREATE UNIQUE INDEX xray_releases_single_flight ON xray_releases(active) WHERE active;
CREATE INDEX xray_release_events_by_release ON xray_release_events(release_id,id);
