//! Validating the generated artifacts against a real xray.
//!
//! Unit tests can only prove that we rendered the fields we believe to be right; they cannot
//! prove xray accepts them. This change gave relay ports a transport layer, and the syntax
//! of those `decryption` / `encryption` strings was copied from `xray vlessenc`, where one
//! mistyped dot means every relay machine fails to start — which only becomes visible after
//! a release.
//!
//! Skipped when no xray binary is available: it is an external tool and should not be a hard
//! dependency of `cargo test`. The path comes from `BROCADE_XRAY_BIN`, falling back to
//! `.tools/xray` at the workspace root (already gitignored).

use std::{
    fs,
    io::Read,
    net::{IpAddr, Ipv4Addr, TcpListener, TcpStream},
    path::PathBuf,
    process::{Command, Stdio},
    thread,
    time::Duration,
};

use brocade_core::{
    artifacts::{
        subscription,
        xray::{self, HOP_HEALTH_BALANCER_TAG},
    },
    format::{json, uri},
    ir::{hops::compile_hops, routing::compile_app, system::compile_system},
    model::{
        Accept, Action, AppView, Chain, DestMatch, Dns, DomainStrategy, EgressDnsAddressStrategy,
        EgressDnsFallback, EgressDnsResolution, EgressDnsTransport, ExternalOutbound,
        ExternalOutboundProtocol, ExternalOutboundSecurity, ExternalVlessTransport,
        ExternalVlessXhttp, ExternalVlessXhttpDownload, ExternalWarpBinding, HopDial,
        HopEncryption, HopIn, HopPool, HopWire, Hysteria2, HysteriaBandwidth, HysteriaCongestion,
        HysteriaMasquerade, HysteriaObfs, Ingress, IngressWires, IpFamily, ModelSnapshot, Node,
        NodeEgressDnsPolicy, ProjectionDownloadEndpoint, ProjectionEndpoint, Reality,
        RealityFallbackLimits, RealityFallbackMode, RealityXhttp, Rule, Step, Tls, TlsXhttp,
        Transport, User, WireGuardKeys, Xhttp, XhttpMode, XhttpXmux,
    },
    physical::{node::project_node, user::project_user},
    Level,
};
use ipnet::Ipv4Net;
use serde_json::{json, Value};

// A real X25519 pair, generated by `xray x25519`. Both REALITY and VLESS Encryption
// validate key length and encoding, so a placeholder like "priv-sg" does not pass.
const HOP_PRIVATE: &str = "iEMzr2SSyraV3pge500qA-3WCTNg0g7qbp4EWqfWQEE";
const HOP_PUBLIC: &str = "cHXdlQzu_QpzURRgNIenuoMGVsD4x925KAH145J3FSg";
const INGRESS_PRIVATE: &str = "gM453ZKs-8Ahf4hPV2SVK1yf7XXC4NLV6V424ETpe2g";
const INGRESS_PUBLIC: &str = "EdUDF5q3f-LSCmqeYUT5AfA3EBJWUAdqzCPHji78pxY";

#[test]
fn machine_egress_dns_without_route_references_loads_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    doc.node_egress_dns = vec![
        NodeEgressDnsPolicy {
            node: "sg".to_owned(),
            position: 0,
            selector: DestMatch::DomainSuffix(vec!["example.com".to_owned()]),
            resolution: EgressDnsResolution {
                address: "192.0.2.53".to_owned(),
                port: 53,
                transport: EgressDnsTransport::Tcp,
                address_strategy: EgressDnsAddressStrategy::UseIpv4,
                fallback: EgressDnsFallback::Stop,
            },
        },
        NodeEgressDnsPolicy {
            node: "sg".to_owned(),
            position: 1,
            selector: DestMatch::DomainKeyword(vec!["ipv6-only".to_owned()]),
            resolution: EgressDnsResolution {
                address: "2001:db8::53".to_owned(),
                port: 5353,
                transport: EgressDnsTransport::Udp,
                address_strategy: EgressDnsAddressStrategy::UseIpv6,
                fallback: EgressDnsFallback::Machine,
            },
        },
    ];
    let egress = app
        .steps
        .iter_mut()
        .find(|step| step.node == "sg")
        .expect("sg 是落地端");
    // No authored route mentions either selector. Machine ownership alone must be enough to emit
    // both DNS servers, their tagged query routes, and their direct outbounds.
    egress.rules.clear();
    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics.iter().all(|d| d.level != Level::Error),
        "{diagnostics:#?}"
    );
    let config = json::xray(&xray::build(&project_node(&sys, &[app_ir], "sg")));
    let path = std::env::temp_dir().join("brocade-xray-machine-egress-dns.json");
    fs::write(&path, &config).unwrap();
    let output = Command::new(&binary)
        .args(["-test", "-c"])
        .arg(&path)
        .output()
        .expect("跑不起来 xray");
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("Configuration OK"),
        "指定落地解析的产物 xray 不认：\n{stdout}\n{}\n----\n{config}",
        String::from_utf8_lossy(&output.stderr),
    );
    let _ = fs::remove_file(&path);
}

#[test]
fn external_proxy_protocols_load_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    doc.external_outbounds = vec![
        ExternalOutbound {
            id: "vless-external".to_owned(),
            tenant: "platform".to_owned(),
            name: "VLESS".to_owned(),
            address: "vless.example.net".to_owned(),
            port: 443,
            protocol: ExternalOutboundProtocol::Vless {
                credential: "6f9d1a8e-2b3c-4d5e-8f70-1a2b3c4d5e6f".to_owned(),
                encryption: "none".to_owned(),
                flow: Some("xtls-rprx-vision".to_owned()),
                transport: ExternalVlessTransport::Raw,
            },
            security: ExternalOutboundSecurity::Reality {
                server_name: "apps.apple.com".to_owned(),
                public_key: INGRESS_PUBLIC.to_owned(),
                short_id: "abcdef0123456789".to_owned(),
                fingerprint: "chrome".to_owned(),
            },
            bindings: Vec::new(),
        },
        ExternalOutbound {
            id: "socks-external".to_owned(),
            tenant: "platform".to_owned(),
            name: "SOCKS5".to_owned(),
            address: "socks.example.net".to_owned(),
            port: 1080,
            protocol: ExternalOutboundProtocol::Socks5 {
                username: Some("proxy-user".to_owned()),
                credential: "proxy-password".to_owned(),
            },
            security: ExternalOutboundSecurity::None,
            bindings: Vec::new(),
        },
        ExternalOutbound {
            id: "xhttp-external".to_owned(),
            tenant: "platform".to_owned(),
            name: "VLESS XHTTP".to_owned(),
            address: "upload.example.net".to_owned(),
            port: 443,
            protocol: ExternalOutboundProtocol::Vless {
                credential: "2c858c84-b8f4-41aa-9296-968fa3ab05d2".to_owned(),
                encryption: "none".to_owned(),
                flow: None,
                transport: ExternalVlessTransport::Xhttp(ExternalVlessXhttp {
                    path: "/external-upload".to_owned(),
                    host: Some("upload-http.example.net".to_owned()),
                    mux: Some(4),
                    mode: XhttpMode::StreamUp,
                    download: Some(ExternalVlessXhttpDownload {
                        address: "download.example.net".to_owned(),
                        port: 8443,
                        security: ExternalOutboundSecurity::Tls {
                            server_name: "download.example.net".to_owned(),
                            fingerprint: "chrome".to_owned(),
                        },
                        path: "/external-download".to_owned(),
                        host: None,
                        mux: Some(2),
                        mode: XhttpMode::Auto,
                    }),
                }),
            },
            security: ExternalOutboundSecurity::Reality {
                server_name: "apps.apple.com".to_owned(),
                public_key: INGRESS_PUBLIC.to_owned(),
                short_id: "abcdef0123456789".to_owned(),
                fingerprint: "chrome".to_owned(),
            },
            bindings: Vec::new(),
        },
        ExternalOutbound {
            id: "http-external".to_owned(),
            tenant: "platform".to_owned(),
            name: "HTTP CONNECT".to_owned(),
            address: "http.example.net".to_owned(),
            port: 443,
            protocol: ExternalOutboundProtocol::HttpConnect {
                username: None,
                credential: String::new(),
            },
            security: ExternalOutboundSecurity::Tls {
                server_name: "http.example.net".to_owned(),
                fingerprint: "chrome".to_owned(),
            },
            bindings: Vec::new(),
        },
        ExternalOutbound {
            id: "ss2022-external".to_owned(),
            tenant: "platform".to_owned(),
            name: "SS2022".to_owned(),
            address: "ss.example.net".to_owned(),
            port: 8388,
            protocol: ExternalOutboundProtocol::Shadowsocks2022 {
                credential: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=".to_owned(),
                method: "2022-blake3-aes-256-gcm".to_owned(),
            },
            security: ExternalOutboundSecurity::None,
            bindings: Vec::new(),
        },
        ExternalOutbound {
            id: "wireguard-external".to_owned(),
            tenant: "platform".to_owned(),
            name: "WireGuard".to_owned(),
            address: "wg.example.net".to_owned(),
            port: 2408,
            protocol: ExternalOutboundProtocol::Wireguard {
                credential: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=".to_owned(),
                peer_public_key: "YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODk=".to_owned(),
                local_addresses: vec!["172.16.0.2/32".to_owned()],
                mtu: 1420,
                reserved: vec![0, 0, 0],
                keep_alive: 25,
                allowed_ips: vec!["0.0.0.0/0".to_owned()],
                no_kernel_tun: true,
                domain_strategy: "ForceIPv4".to_owned(),
            },
            security: ExternalOutboundSecurity::None,
            bindings: Vec::new(),
        },
    ];
    app.steps[0].rules = [
        "vless-external",
        "socks-external",
        "xhttp-external",
        "http-external",
        "ss2022-external",
        "wireguard-external",
    ]
    .into_iter()
    .enumerate()
    .map(|(index, outbound)| Rule {
        dest_match: if index == 5 {
            DestMatch::Any
        } else {
            DestMatch::DomainSuffix(vec![format!("case-{index}.example")])
        },
        action: Action::Proxy {
            outbound: outbound.to_owned(),
        },
    })
    .collect();
    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    let config = json::xray(&xray::build(&project_node(&sys, &[app_ir], "hk")));
    let path = std::env::temp_dir().join("brocade-xray-external-protocols.json");
    fs::write(&path, &config).unwrap();
    let output = Command::new(&binary)
        .args(["-test", "-c"])
        .arg(&path)
        .output()
        .expect("跑不起来 xray");
    let _ = fs::remove_file(&path);
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("Configuration OK"),
        "外部协议产物 xray 不认：\n{stdout}\n{}\n----\n{config}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn managed_warp_binding_lowers_into_a_config_the_real_binary_accepts() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    doc.external_outbounds = vec![ExternalOutbound {
        id: "warp".to_owned(),
        tenant: "platform".to_owned(),
        name: "Cloudflare WARP".to_owned(),
        address: "engage.cloudflareclient.com".to_owned(),
        port: 2408,
        protocol: ExternalOutboundProtocol::Warp {
            mtu: 1280,
            keep_alive: 25,
            allowed_ips: vec!["0.0.0.0/0".to_owned(), "::/0".to_owned()],
            no_kernel_tun: true,
            domain_strategy: "ForceIP".to_owned(),
            workers: 4,
        },
        security: ExternalOutboundSecurity::None,
        bindings: vec![ExternalWarpBinding {
            node: "hk".to_owned(),
            device_id: "device-hk".to_owned(),
            account_id: "account-hk".to_owned(),
            registered_at: "2026-08-27T00:00:00.000Z".to_owned(),
            endpoint_address: None,
            endpoint_port: None,
            mtu: None,
            keep_alive: None,
            allowed_ips: None,
            no_kernel_tun: None,
            domain_strategy: None,
            workers: None,
            private_key: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=".to_owned(),
            peer_public_key: "YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODk=".to_owned(),
            local_addresses: vec![
                "172.16.0.2/32".to_owned(),
                "2606:4700:110:8::2/128".to_owned(),
            ],
            reserved: vec![1, 2, 3],
        }],
    }];
    app.steps[0].rules = vec![Rule {
        dest_match: DestMatch::Any,
        action: Action::Proxy {
            outbound: "warp".to_owned(),
        },
    }];

    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.level != Level::Error),
        "{diagnostics:#?}"
    );
    let config = json::xray(&xray::build(&project_node(&sys, &[app_ir], "hk")));
    let parsed = serde_json::from_str::<Value>(&config).unwrap();
    let warp = parsed["outbounds"]
        .as_array()
        .unwrap()
        .iter()
        .find(|outbound| outbound["tag"] == "out:external/warp")
        .expect("managed WARP outbound");
    assert_eq!(warp["protocol"], "wireguard");
    assert_eq!(warp["settings"]["reserved"], json!([1, 2, 3]));

    let path = std::env::temp_dir().join("brocade-xray-managed-warp.json");
    fs::write(&path, &config).unwrap();
    let output = Command::new(&binary)
        .args(["-test", "-c"])
        .arg(&path)
        .output()
        .expect("跑不起来 xray");
    let _ = fs::remove_file(&path);
    assert!(
        output.status.success(),
        "managed WARP 产物 xray 不认：\n{}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn generated_xray_configs_load_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };

    let cases = [
        ("overlay-hop", HopDial::Overlay, HopWire::None),
        (
            "direct-hop-encryption",
            HopDial::Addr("relay.sg.example:8443".to_owned()),
            HopWire::Encryption(HopEncryption {
                private_key: HOP_PRIVATE.to_owned(),
                public_key: HOP_PUBLIC.to_owned(),
            }),
        ),
        (
            "direct-hop-reality",
            HopDial::Addr("relay.sg.example:443".to_owned()),
            HopWire::Reality(Reality {
                private_key: HOP_PRIVATE.to_owned(),
                public_key: HOP_PUBLIC.to_owned(),
                short_ids: vec!["0123456789abcdef".to_owned()],
                dest: "apps.apple.com:443".to_owned(),
                server_names: vec!["apps.apple.com".to_owned()],
                fingerprint: "chrome".to_owned(),
                flow: None,
            }),
        ),
    ];

    for (name, dial, security) in cases {
        let (sys, app_ir) = fixture(dial, security);
        // Both machines are validated: sg is the receiving side (inbound + decryption) and
        // hk the dialing side (outbound + encryption), and a syntax error on either must be
        // caught.
        for node_id in ["sg", "hk"] {
            let config = json::xray(&xray::build(&project_node(
                &sys,
                std::slice::from_ref(&app_ir),
                node_id,
            )));
            let path = std::env::temp_dir().join(format!("brocade-xray-{name}-{node_id}.json"));
            fs::write(&path, &config).unwrap();

            let output = Command::new(&binary)
                .args(["-test", "-c"])
                .arg(&path)
                .output()
                .expect("跑不起来 xray");
            let stdout = String::from_utf8_lossy(&output.stdout);
            let stderr = String::from_utf8_lossy(&output.stderr);
            assert!(
                stdout.contains("Configuration OK"),
                "{name}/{node_id} 的产物 xray 不认：\n{stdout}\n{stderr}\n----\n{config}"
            );
            let _ = fs::remove_file(&path);
        }
    }
}

/// The share link's `extra`, put back through the binary that has to read it.
///
/// The connection pool has exactly one way into an XHTTP share link: `extra`, whose contents
/// xray does not merge but *substitutes* — `SplitHTTPConfig::Build` unmarshals it into a fresh
/// config, copies `host`, `path` and `mode` back onto it and then keeps the new one. So the
/// question a unit test cannot answer is whether the block we emit survives that, and whether it
/// is read at all: an unknown key inside `xhttpSettings` would pass `-test` in silence, and the
/// setting would be gone without a word.
///
/// The second half is what makes this a check rather than a formality. A concurrency xray must
/// refuse has to actually be refused; if it passes, `extra` is being ignored and the first
/// assertion proved nothing.
#[test]
fn the_share_link_extra_carries_the_pool_into_a_config_the_real_binary_reads() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };

    let (doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    app.ingresses[0].wires = IngressWires::Vless(Transport::VlessRealityXhttp(RealityXhttp {
        reality: app.ingresses[0].wires.reality().unwrap().clone(),
        xhttp: Xhttp {
            path: "/pool".to_owned(),
            host: None,
            // One: a connection per stream, reused once it goes idle. The whole point of the
            // exercise, and the value that used to reach no client at all.
            xmux: Some(XhttpXmux::with_concurrency(1)),
            tuning: None,
            mode: XhttpMode::Auto,
        },
    }));
    app.ingresses[0].wires.set_flow(None);
    app.grants.push(brocade_core::model::Grant {
        tenant: "platform".to_owned(),
        user: "alice".to_owned(),
        ingress: "i-relay".to_owned(),
    });

    let mut diagnostics = Vec::new();
    let app_ir = compile_app(&doc, &app, &mut diagnostics);
    assert!(
        diagnostics.iter().all(|d| d.level != Level::Error),
        "{diagnostics:#?}"
    );
    let uri_text = uri::subscription(&subscription::build(&project_user(
        &[app_ir],
        "platform",
        "alice",
    )));

    let extra = share_link_extra(&uri_text);
    assert_eq!(
        extra,
        json!({
            "xmux": {
                "maxConcurrency": 1,
                "hMaxRequestTimes": "600-900",
                "hMaxReusableSecs": "1800-3000"
            }
        }),
        "{uri_text}"
    );

    assert!(
        client_config_loads(&binary, "pool", &extra),
        "带 extra 的客户端配置 xray 不认：{extra}"
    );
    assert!(
        !client_config_loads(
            &binary,
            "pool-negative",
            &json!({ "xmux": { "maxConcurrency": "十六" } })
        ),
        "xray 收下了一个非法并发，说明它根本没在读 extra——上面那条断言什么也没证明"
    );
}

/// The value of the `extra` query parameter, decoded. Panics rather than returning an option:
/// every caller here has just asserted the link should carry one.
fn share_link_extra(uri_text: &str) -> Value {
    let raw = uri_text
        .split(['?', '&'])
        .find_map(|pair| pair.strip_prefix("extra="))
        .unwrap_or_else(|| panic!("链接里没有 extra：{uri_text}"))
        .split('#')
        .next()
        .unwrap();
    let mut bytes = Vec::new();
    let mut chars = raw.chars();
    while let Some(c) = chars.next() {
        if c == '%' {
            let hex: String = chars.by_ref().take(2).collect();
            bytes.push(u8::from_str_radix(&hex, 16).unwrap());
        } else {
            bytes.push(c as u8);
        }
    }
    serde_json::from_slice(&bytes).unwrap()
}

/// Does xray build a client outbound out of this `extra`? The shape around it is the one a
/// share link importer writes: `extra` sits inside `xhttpSettings`, beside the three keys the
/// substitution copies back.
fn client_config_loads(binary: &std::path::Path, name: &str, extra: &Value) -> bool {
    let config = serde_json::to_string_pretty(&json!({
        "outbounds": [{
            "protocol": "vless",
            "settings": { "vnext": [{
                "address": "hk.example.net",
                "port": 443,
                "users": [{ "id": "6f9d1a8e-2b3c-4d5e-8f70-1a2b3c4d5e6f", "encryption": "none" }],
            }]},
            "streamSettings": {
                "network": "xhttp",
                "security": "reality",
                "realitySettings": {
                    "serverName": "apps.apple.com",
                    "fingerprint": "chrome",
                    "publicKey": INGRESS_PUBLIC,
                    "shortId": "abcdef0123456789",
                },
                "xhttpSettings": { "path": "/pool", "extra": extra },
            },
        }],
    }))
    .unwrap();
    let path = std::env::temp_dir().join(format!("brocade-xray-extra-{name}.json"));
    fs::write(&path, &config).unwrap();
    let output = Command::new(binary)
        .args(["-test", "-c"])
        .arg(&path)
        .output()
        .expect("跑不起来 xray");
    let _ = fs::remove_file(&path);
    String::from_utf8_lossy(&output.stdout).contains("Configuration OK")
}

/// The reverse tunnel's two ends, checked against a real xray.
///
/// This is the case whose absence let a whole release ship a config xray refuses: the
/// compiler kept emitting the top-level `reverse` block long after xray removed it, and
/// every unit test stayed green because they only assert on fields we chose to render.
/// The node was the first thing to notice, by not starting.
#[test]
fn the_reverse_tunnel_loads_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    assert!(
        !accepts_legacy_reverse(&binary),
        "这个 xray 还认 legacy reverse，比机队跑的版本旧。\n\
         它会静默忽略我们现在写在 client 上的 `reverse`，于是这条测试通过却什么也没证明。\n\
         换成机队钉的版本：{}",
        binary.display()
    );

    let (sys, app_ir) = reverse_fixture();
    // Both ends, and for opposite reasons: the portal side must accept `reverse` on a
    // client entry, the bridge side must accept it on a flat outbound. Either one alone
    // would leave half the pair unverified.
    for node_id in ["hk", "sg"] {
        let config = json::xray(&xray::build(&project_node(
            &sys,
            std::slice::from_ref(&app_ir),
            node_id,
        )));
        let path = std::env::temp_dir().join(format!("brocade-xray-reverse-{node_id}.json"));
        fs::write(&path, &config).unwrap();
        let output = Command::new(&binary)
            .args(["-test", "-c"])
            .arg(&path)
            .output()
            .expect("跑不起来 xray");
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stdout.contains("Configuration OK"),
            "reverse/{node_id} 的产物 xray 不认：\n{stdout}\n{stderr}\n----\n{config}"
        );
        let _ = fs::remove_file(&path);
    }
}

/// Whether this binary still understands the removed top-level `reverse` block.
///
/// A version check by string would have to track every future release; this asks the
/// binary the only question that matters, and it answers in its own terms.
fn accepts_legacy_reverse(binary: &PathBuf) -> bool {
    let path = std::env::temp_dir().join("brocade-xray-legacy-probe.json");
    fs::write(
        &path,
        r#"{"reverse":{"portals":[{"tag":"p","domain":"x.internal"}],"bridges":[]},
            "inbounds":[],"outbounds":[{"tag":"o","protocol":"blackhole"}]}"#,
    )
    .unwrap();
    let output = Command::new(binary)
        .args(["-test", "-c"])
        .arg(&path)
        .output()
        .expect("跑不起来 xray");
    let _ = fs::remove_file(&path);
    String::from_utf8_lossy(&output.stdout).contains("Configuration OK")
}

/// hk is the portal (public, hosts the relay port), sg the bridge (behind NAT, dials
/// out). The asymmetry is the point: only the upstream has a `hop_in`.
fn reverse_fixture() -> (
    brocade_core::ir::system::SystemIr,
    brocade_core::ir::routing::AppIr,
) {
    let (sys_doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    app.steps = vec![
        Step {
            chain: "c-relay".to_owned(),
            node: "hk".to_owned(),
            accept: Some(Accept {
                uuid: "2c3b4d5e-6f70-4a8b-9c0d-1e2f3a4b5c6d".to_owned(),
                label: "c-relay@hk".to_owned(),
            }),
            hop_in: Some(HopIn {
                port: 20000,
                security: HopWire::None,
            }),
            rules: vec![Rule {
                dest_match: DestMatch::Any,
                action: Action::Forward {
                    to: "sg".to_owned(),
                    dial: HopDial::Reverse(IpFamily::V4),
                    pool: HopPool::None,
                },
            }],
        },
        Step {
            chain: "c-relay".to_owned(),
            node: "sg".to_owned(),
            accept: Some(Accept {
                uuid: "3d4e5f60-7081-4b9c-8d0e-2f3a4b5c6d7e".to_owned(),
                label: "c-relay@sg".to_owned(),
            }),
            // No listening port: this machine is behind NAT, which is the whole reason
            // the hop is reversed.
            hop_in: None,
            rules: vec![Rule {
                dest_match: DestMatch::Any,
                action: Action::Egress { send_through: None },
            }],
        },
    ];

    let mut diagnostics = Vec::new();
    let sys = compile_system(&sys_doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&sys_doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics.iter().all(|d| d.level != Level::Error),
        "{diagnostics:#?}"
    );
    (sys, app_ir)
}

fn xray_binary() -> Option<PathBuf> {
    let path = match std::env::var_os("BROCADE_XRAY_BIN") {
        Some(value) => PathBuf::from(value),
        None => PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()?
            .parent()?
            .join(".tools/xray"),
    };
    path.is_file().then_some(path)
}

/// An XHTTP ingress, checked against the real binary.
///
/// Worth its own case because this is exactly the pair xray's own `-test` cannot judge. It
/// answers `Configuration OK` to an XHTTP ingress carrying Vision — a combination the running
/// server then refuses on every connection — so the compiler is what has to refuse it, and this
/// test guards the other half: that what the compiler *does* emit is something xray accepts.
#[test]
fn an_xhttp_ingress_loads_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };

    // Every mode string is here for a reason beyond coverage: xray refuses an unknown one at
    // build time (`unsupported mode: …`), so this is what checks our spellings against the
    // binary rather than against a doc page.
    for (name, mux, mode) in [
        ("xhttp-plain", None, XhttpMode::Auto),
        ("xhttp-mux", Some(16u16), XhttpMode::Auto),
        ("xhttp-packet-up", None, XhttpMode::PacketUp),
        ("xhttp-stream-up", None, XhttpMode::StreamUp),
        ("xhttp-stream-one", None, XhttpMode::StreamOne),
    ] {
        let (doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
        app.ingresses[0].wires = IngressWires::Vless(Transport::VlessRealityXhttp(RealityXhttp {
            reality: app.ingresses[0].wires.reality().unwrap().clone(),
            xhttp: Xhttp {
                path: "/probe".to_owned(),
                host: None,
                xmux: mux.map(XhttpXmux::with_concurrency),
                tuning: None,
                mode,
            },
        }));
        // Vision is the default and cannot ride XHTTP; the compiler refuses the pair, so the
        // model reaching xray always has it off.
        app.ingresses[0].wires.set_flow(None);

        let mut diagnostics = Vec::new();
        let sys = compile_system(&doc, &mut diagnostics);
        let app_ir = compile_hops(
            compile_app(&doc, &app, &mut diagnostics),
            &sys,
            &mut diagnostics,
        );
        assert!(
            diagnostics.iter().all(|d| d.level != Level::Error),
            "{diagnostics:#?}"
        );

        let config = json::xray(&xray::build(&project_node(
            &sys,
            std::slice::from_ref(&app_ir),
            "hk",
        )));
        let value: Value = serde_json::from_str(&config).unwrap();
        let subscriber = value["inbounds"]
            .as_array()
            .unwrap()
            .iter()
            .find(|inbound| inbound["tag"] == "in:relay/i-relay")
            .expect("subscriber XHTTP inbound");
        assert_eq!(
            subscriber["streamSettings"]["sockopt"]["tcpFastOpen"], 256,
            "XHTTP subscriber listener must enable TFO: {subscriber:#?}"
        );
        assert!(
            config.contains("\"network\": \"xhttp\"") && config.contains("\"path\": \"/probe\""),
            "产物里没有 xhttp 的痕迹：\n{config}"
        );
        match mode.as_str() {
            Some(spelling) => assert!(
                config.contains(&format!("\"mode\": \"{spelling}\"")),
                "产物里没写上行姿势 {spelling}：\n{config}"
            ),
            // The default is written nowhere: a server that names a mode refuses every client
            // naming another, so an unasked-for value would lock out subscriptions already issued.
            None => assert!(
                !config.contains("\"mode\""),
                "没人选的时候不该写 mode：\n{config}"
            ),
        }

        let path = std::env::temp_dir().join(format!("brocade-xray-{name}.json"));
        fs::write(&path, &config).unwrap();
        let output = Command::new(&binary)
            .args(["-test", "-c"])
            .arg(&path)
            .output()
            .expect("跑不起来 xray");
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains("Configuration OK"),
            "{name} 的产物 xray 不认：\n{stdout}\n{}\n----\n{config}",
            String::from_utf8_lossy(&output.stderr)
        );
        let _ = fs::remove_file(&path);
    }
}

#[test]
fn split_reality_upload_and_tls_download_load_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    app.ingresses[0].wires = IngressWires::Vless(Transport::VlessRealityXhttp(RealityXhttp {
        reality: app.ingresses[0].wires.reality().unwrap().clone(),
        xhttp: Xhttp {
            path: "/split-probe".to_owned(),
            host: None,
            xmux: Some(XhttpXmux::with_concurrency(8)),
            tuning: None,
            mode: XhttpMode::Auto,
        },
    }));
    app.ingresses[0].wires.set_flow(None);
    app.ingresses[0].projection.v4 = Some(ProjectionEndpoint {
        host: "198.51.100.20".to_owned(),
        port: 443,
        download: Some(ProjectionDownloadEndpoint {
            host: "cdn.example.net".to_owned(),
            port: 443,
            origin_port: Some(8443),
            http_host: None,
            mux: None,
        }),
    });
    doc.nodes
        .iter_mut()
        .find(|node| node.id == "hk")
        .unwrap()
        .certificate_name = Some("origin.example.net".to_owned());

    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics.iter().all(|d| d.level != Level::Error),
        "{diagnostics:#?}"
    );
    let config = json::xray(&xray::build(&project_node(
        &sys,
        std::slice::from_ref(&app_ir),
        "hk",
    )));
    let value: Value = serde_json::from_str(&config).unwrap();
    let inbounds = value["inbounds"].as_array().unwrap();
    assert!(inbounds.iter().any(|inbound| {
        inbound["tag"] == "in:relay/i-relay"
            && inbound["listen"] == "127.0.0.1"
            && inbound["streamSettings"]["network"] == "xhttp"
            && inbound["streamSettings"]["security"] == "none"
    }));
    assert!(inbounds.iter().any(|inbound| {
        inbound["tag"] == "in:relay/i-relay:upload"
            && inbound["protocol"] == "dokodemo-door"
            && inbound["streamSettings"]["security"] == "reality"
    }));
    assert!(inbounds.iter().any(|inbound| {
        inbound["tag"] == "in:relay/i-relay:download:8443"
            && inbound["protocol"] == "dokodemo-door"
            && inbound["streamSettings"]["security"] == "tls"
    }));
    assert!(value["routing"]["rules"]
        .as_array()
        .unwrap()
        .iter()
        .any(|rule| {
            rule["inboundTag"].as_array().is_some_and(|tags| {
                tags.iter().any(|tag| tag == "in:relay/i-relay:upload")
                    && tags
                        .iter()
                        .any(|tag| tag == "in:relay/i-relay:download:8443")
            }) && rule["outboundTag"] == "out:internal"
        }));

    let dir = std::env::temp_dir().join("brocade-xray-split");
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    let (certificate, key) = self_signed();
    fs::write(dir.join("cert.pem"), certificate).unwrap();
    fs::write(dir.join("key.pem"), key).unwrap();
    let path = dir.join("split.json");
    fs::write(
        &path,
        config
            .replace(
                xray::NODE_CERTIFICATE_FILE,
                &dir.join("cert.pem").display().to_string(),
            )
            .replace(
                xray::NODE_CERTIFICATE_KEY_FILE,
                &dir.join("key.pem").display().to_string(),
            ),
    )
    .unwrap();
    let output = Command::new(&binary)
        .args(["-test", "-c"])
        .arg(&path)
        .output()
        .expect("跑不起来 xray");
    assert!(
        String::from_utf8_lossy(&output.stdout).contains("Configuration OK"),
        "分离产物 xray 不认：\n{}\n{}\n----\n{config}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn ordinary_https_to_reality_reaches_only_the_local_403_cover() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    if Command::new("curl").arg("--version").output().is_err() {
        eprintln!("跳过：没找到 curl");
        return;
    }

    let ports = free_tcp_ports(2);
    let public_port = ports[0];
    let runtime_cover_port = ports[1];
    let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    app.ingresses[0].port = public_port;
    let reality = app.ingresses[0].wires.reality_mut().unwrap();
    reality.fallback_mode = RealityFallbackMode::NodeCertificate;
    reality.fallback_limits = RealityFallbackLimits::Strict;
    let hk = doc.nodes.iter_mut().find(|node| node.id == "hk").unwrap();
    hk.certificate_name = Some("a1b2c3d4.example.net".to_owned());
    hk.api_port = None;

    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.level != Level::Error),
        "{diagnostics:#?}"
    );
    let artifact = xray::build(&project_node(&sys, &[app_ir], "hk"));
    let mut value: Value = serde_json::from_str(&json::xray(&artifact)).unwrap();
    let inbounds = value["inbounds"].as_array_mut().unwrap();
    let reality = inbounds
        .iter_mut()
        .find(|inbound| inbound["tag"] == "in:relay/i-relay")
        .expect("REALITY inbound");
    reality["streamSettings"]["realitySettings"]["dest"] =
        json!(format!("127.0.0.1:{runtime_cover_port}"));
    let cover = inbounds
        .iter_mut()
        .find(|inbound| inbound["tag"] == "in:relay/i-relay:cover")
        .expect("cover inbound");
    cover["port"] = json!(runtime_cover_port);

    let dir = std::env::temp_dir().join(format!("brocade-reality-cover-{public_port}"));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    let (certificate, key) = self_signed();
    let certificate_path = dir.join("cert.pem");
    let key_path = dir.join("key.pem");
    fs::write(&certificate_path, certificate).unwrap();
    fs::write(&key_path, key).unwrap();
    let config = serde_json::to_string_pretty(&value)
        .unwrap()
        .replace(
            xray::NODE_CERTIFICATE_FILE,
            &certificate_path.display().to_string(),
        )
        .replace(
            xray::NODE_CERTIFICATE_KEY_FILE,
            &key_path.display().to_string(),
        );
    assert!(!config.contains("apps.apple.com"), "{config}");
    let config_path = dir.join("xray.json");
    fs::write(&config_path, &config).unwrap();
    let checked = Command::new(&binary)
        .args(["-test", "-c"])
        .arg(&config_path)
        .output()
        .expect("跑不起来 xray -test");
    assert!(
        checked.status.success(),
        "本地 cover 产物 xray 不认：\n{}\n{}\n----\n{config}",
        String::from_utf8_lossy(&checked.stdout),
        String::from_utf8_lossy(&checked.stderr)
    );

    let mut child = Command::new(&binary)
        .args(["run", "-c"])
        .arg(&config_path)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .expect("跑不起来 xray");
    let ready = (0..50).any(|_| {
        if TcpStream::connect((Ipv4Addr::LOCALHOST, public_port)).is_ok() {
            true
        } else {
            thread::sleep(Duration::from_millis(50));
            false
        }
    });
    let response = ready.then(|| {
        Command::new("curl")
            .args([
                "--silent",
                "--show-error",
                "--include",
                "--max-time",
                "5",
                "--noproxy",
                "*",
                "--cacert",
            ])
            .arg(&certificate_path)
            .arg("--resolve")
            .arg(format!("a1b2c3d4.example.net:{public_port}:127.0.0.1"))
            .arg(format!("https://a1b2c3d4.example.net:{public_port}/"))
            .output()
            .expect("跑不起来 curl")
    });
    let _ = child.kill();
    let _ = child.wait();
    let _ = fs::remove_dir_all(&dir);

    assert!(ready, "xray 没有监听 REALITY 公网口");
    let response = response.unwrap();
    let stdout = String::from_utf8_lossy(&response.stdout);
    let stderr = String::from_utf8_lossy(&response.stderr);
    assert!(response.status.success(), "curl 失败：{stderr}\n{stdout}");
    assert!(stdout.starts_with("HTTP/1.1 403"), "{stdout}");
}

#[test]
fn valid_reality_traffic_still_passes_with_the_local_cover_enabled() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    if Command::new("curl").arg("--version").output().is_err() {
        eprintln!("跳过：没找到 curl");
        return;
    }

    const USER_UUID: &str = "6f9d1a8e-2b3c-4d5e-8f70-1a2b3c4d5e6f";
    let ports = free_tcp_ports(3);
    let public_port = ports[0];
    let runtime_cover_port = ports[1];
    let socks_port = ports[2];

    let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    app.ingresses[0].port = public_port;
    let reality = app.ingresses[0].wires.reality_mut().unwrap();
    reality.fallback_mode = RealityFallbackMode::NodeCertificate;
    reality.fallback_limits = RealityFallbackLimits::Balanced;
    app.steps = vec![Step {
        chain: "c-relay".to_owned(),
        node: "hk".to_owned(),
        accept: None,
        hop_in: None,
        rules: vec![Rule {
            dest_match: DestMatch::Any,
            action: Action::Egress { send_through: None },
        }],
    }];
    let hk = doc.nodes.iter_mut().find(|node| node.id == "hk").unwrap();
    hk.certificate_name = Some("a1b2c3d4.example.net".to_owned());
    hk.api_port = None;

    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.level != Level::Error),
        "{diagnostics:#?}"
    );
    let mut server: Value = serde_json::from_str(&json::xray(&xray::build(&project_node(
        &sys,
        &[app_ir],
        "hk",
    ))))
    .unwrap();
    let inbounds = server["inbounds"].as_array_mut().unwrap();
    let public = inbounds
        .iter_mut()
        .find(|inbound| inbound["tag"] == "in:relay/i-relay")
        .unwrap();
    public["settings"]["clients"] = json!([{
        "id": USER_UUID,
        "email": "test-user",
        "level": 0,
    }]);
    public["streamSettings"]["realitySettings"]["dest"] =
        json!(format!("127.0.0.1:{runtime_cover_port}"));
    inbounds
        .iter_mut()
        .find(|inbound| inbound["tag"] == "in:relay/i-relay:cover")
        .unwrap()["port"] = json!(runtime_cover_port);
    let business_outbound = server["outbounds"]
        .as_array_mut()
        .unwrap()
        .iter_mut()
        .find(|outbound| outbound["tag"] == "out:egress")
        .unwrap();
    business_outbound["protocol"] = json!("blackhole");
    business_outbound["settings"] = json!({ "response": { "type": "http" } });

    let dir = std::env::temp_dir().join(format!("brocade-reality-valid-{public_port}"));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    let (certificate, key) = self_signed();
    let certificate_path = dir.join("cert.pem");
    let key_path = dir.join("key.pem");
    fs::write(&certificate_path, certificate).unwrap();
    fs::write(&key_path, key).unwrap();
    let server_log = dir.join("server.log");
    let client_log = dir.join("client.log");
    server["log"] = json!({
        "loglevel": "info",
        "access": "none",
        "error": server_log,
    });
    let server_config = serde_json::to_string_pretty(&server)
        .unwrap()
        .replace(
            xray::NODE_CERTIFICATE_FILE,
            &certificate_path.display().to_string(),
        )
        .replace(
            xray::NODE_CERTIFICATE_KEY_FILE,
            &key_path.display().to_string(),
        );
    let server_path = dir.join("server.json");
    fs::write(&server_path, server_config).unwrap();
    let client_path = dir.join("client.json");
    fs::write(
        &client_path,
        serde_json::to_string_pretty(&json!({
            "log": { "loglevel": "info", "access": "none", "error": client_log },
            "inbounds": [{
                "tag": "probe-in",
                "listen": "127.0.0.1",
                "port": socks_port,
                "protocol": "socks",
                "settings": { "auth": "noauth", "udp": false },
            }],
            "outbounds": [{
                "tag": "probe-out",
                "protocol": "vless",
                "settings": { "vnext": [{
                    "address": "127.0.0.1",
                    "port": public_port,
                    "users": [{ "id": USER_UUID, "encryption": "none" }],
                }]},
                "streamSettings": {
                    "network": "tcp",
                    "security": "reality",
                    "realitySettings": {
                        "serverName": "a1b2c3d4.example.net",
                        "fingerprint": "chrome",
                        "publicKey": INGRESS_PUBLIC,
                        "shortId": "abcdef0123456789",
                    },
                },
            }],
        }))
        .unwrap(),
    )
    .unwrap();

    let mut server_process = Command::new(&binary)
        .args(["run", "-c"])
        .arg(&server_path)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    let server_ready = (0..50).any(|_| {
        if TcpStream::connect((Ipv4Addr::LOCALHOST, public_port)).is_ok() {
            true
        } else {
            thread::sleep(Duration::from_millis(50));
            false
        }
    });
    let mut client_process = server_ready.then(|| {
        Command::new(&binary)
            .args(["run", "-c"])
            .arg(&client_path)
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .unwrap()
    });
    let client_ready = client_process.as_ref().is_some_and(|_| {
        (0..50).any(|_| {
            if TcpStream::connect((Ipv4Addr::LOCALHOST, socks_port)).is_ok() {
                true
            } else {
                thread::sleep(Duration::from_millis(50));
                false
            }
        })
    });
    let response = client_ready.then(|| {
        Command::new("curl")
            .args([
                "--silent",
                "--show-error",
                "--include",
                "--max-time",
                "5",
                "--noproxy",
                "",
                "--socks5-hostname",
            ])
            .arg(format!("127.0.0.1:{socks_port}"))
            // The business outbound is an HTTP blackhole in this test. A 403 can only get back
            // through the SOCKS client after REALITY authentication, VLESS parsing, and routing.
            .arg("http://93.184.216.34/")
            .output()
            .unwrap()
    });
    if let Some(process) = &mut client_process {
        let _ = process.kill();
        let _ = process.wait();
    }
    let _ = server_process.kill();
    let _ = server_process.wait();
    let server_log_text = fs::read_to_string(&server_log).unwrap_or_default();
    let client_log_text = fs::read_to_string(&client_log).unwrap_or_default();
    let _ = fs::remove_dir_all(&dir);

    assert!(server_ready, "server xray 没有监听 REALITY 入口");
    assert!(client_ready, "client xray 没有监听 SOCKS 入口");
    let response = response.unwrap();
    assert!(
        response.status.success(),
        "curl 失败：{}\nserver:\n{server_log_text}\nclient:\n{client_log_text}",
        String::from_utf8_lossy(&response.stderr),
    );
    assert!(
        String::from_utf8_lossy(&response.stdout).starts_with("HTTP/1.1 403"),
        "{}",
        String::from_utf8_lossy(&response.stdout),
    );
    assert!(
        server_log_text.contains("proxy/vless/inbound: received request"),
        "合法 REALITY 流量没有进入 VLESS：\n{server_log_text}"
    );
    assert!(
        server_log_text.contains("taking detour [out:egress]"),
        "合法 REALITY 流量没有进入业务出站：\n{server_log_text}"
    );
}

/// The guard's claim, put to the running binary: a fallback asking for a name this ingress does
/// not borrow never reaches the borrowed site, while one asking for the borrowed name still does.
///
/// Asserted on the site's side of the door rather than the client's. Neither curl completes a
/// handshake here — the stand-in site is a bare socket — so the client cannot tell the two cases
/// apart, and a test written from there would pass with the guard removed. What separates them is
/// whether the connection arrived at all.
///
/// Both halves are needed. Without the borrowed name still getting through, "nothing arrives
/// ever" would satisfy the deny half, and that is also what a mis-ordered rule table produces —
/// the failure mode where REALITY quietly stops working while every field still reads right.
#[test]
fn a_fallback_asking_for_another_name_never_reaches_the_borrowed_site() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    if Command::new("curl").arg("--version").output().is_err() {
        eprintln!("跳过：没找到 curl");
        return;
    }

    const BORROWED: &str = "a1b2c3d4.example.net";
    const STRANGER: &str = "e5f6a7b8.example.net";
    let ports = free_tcp_ports(3);
    let public_port = ports[0];
    let site_port = ports[1];
    // The guard's own port is not left where the compiler put it. That port comes out of a fixed
    // internal range starting at 61101 — right for a machine, which runs one xray, and wrong here,
    // where the sibling tests in this file are running their own at the same moment. xray listens
    // with SO_REUSEPORT, so a second process binding the same loopback port does not fail: the
    // kernel hands each of them a share of the connections, and the fallback this test is reading
    // gets answered by another test's routing table. That failure is silent from both ends — this
    // process logs a listener it is only partly serving, and the knock simply never arrives.
    let runtime_guard_port = ports[2];
    // The borrowed site, standing in as a socket that accepts and says nothing. Bound before xray
    // starts so that a connection can never be lost to a race with the listener coming up.
    let site = TcpListener::bind((Ipv4Addr::LOCALHOST, site_port)).unwrap();
    site.set_nonblocking(true).unwrap();

    let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    app.ingresses[0].port = public_port;
    let reality = app.ingresses[0].wires.reality_mut().unwrap();
    reality.fallback_mode = RealityFallbackMode::CustomSite;
    reality.dest = format!("{BORROWED}:{site_port}");
    reality.server_names = vec![BORROWED.to_owned()];
    reality.fallback_limits = RealityFallbackLimits::Off;
    let hk = doc.nodes.iter_mut().find(|node| node.id == "hk").unwrap();
    hk.api_port = None;

    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.level != Level::Error),
        "{diagnostics:#?}"
    );
    let mut value: Value = serde_json::from_str(&json::xray(&xray::build(&project_node(
        &sys,
        &[app_ir],
        "hk",
    ))))
    .unwrap();
    let inbounds = value["inbounds"].as_array_mut().unwrap();
    let guard = inbounds
        .iter_mut()
        .find(|inbound| inbound["tag"] == "in:relay/i-relay:guard")
        .expect("guard inbound");
    assert_eq!(guard["settings"]["address"], BORROWED);
    assert_eq!(guard["settings"]["port"], site_port);
    let compiled_guard_port = guard["port"].as_u64().expect("guard 有端口");
    // The borrowed name resolves nowhere on this machine. Only the address is swapped; the name
    // the routing rule matches on is the one the artifact wrote.
    guard["settings"]["address"] = json!("127.0.0.1");
    guard["port"] = json!(runtime_guard_port);
    let public = inbounds
        .iter_mut()
        .find(|inbound| inbound["tag"] == "in:relay/i-relay")
        .expect("REALITY inbound");
    // Asserted before being moved, because the whole test rests on it: the fallback reaches the
    // guard only if the artifact aimed `dest` there, and a run with the two ends on different
    // ports would fail for a reason that has nothing to do with the guard.
    assert_eq!(
        public["streamSettings"]["realitySettings"]["dest"],
        json!(format!("127.0.0.1:{compiled_guard_port}")),
    );
    public["streamSettings"]["realitySettings"]["dest"] =
        json!(format!("127.0.0.1:{runtime_guard_port}"));

    let dir = std::env::temp_dir().join(format!("brocade-reality-guard-{public_port}"));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    // Which outbound each knock was handed to. Read as well as the arrivals because arrival alone
    // does not name a culprit: unmatched traffic falls to the first outbound, and on this fixture
    // that one is a relay dial to a machine which is not running — so deleting the deny rule
    // entirely still strands the stranger, and a test reading only the socket stays green.
    let error_log = dir.join("error.log");
    value["log"] = json!({ "loglevel": "info", "access": "none", "error": error_log });
    let config_path = dir.join("xray.json");
    fs::write(&config_path, serde_json::to_string_pretty(&value).unwrap()).unwrap();
    let checked = Command::new(&binary)
        .args(["-test", "-c"])
        .arg(&config_path)
        .output()
        .expect("跑不起来 xray -test");
    assert!(
        checked.status.success(),
        "带 guard 的产物 xray 不认：\n{}\n{}",
        String::from_utf8_lossy(&checked.stdout),
        String::from_utf8_lossy(&checked.stderr)
    );

    let mut child = Command::new(&binary)
        .args(["run", "-c"])
        .arg(&config_path)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .expect("跑不起来 xray");
    let ready = (0..50).any(|_| {
        if TcpStream::connect((Ipv4Addr::LOCALHOST, public_port)).is_ok() {
            true
        } else {
            thread::sleep(Duration::from_millis(50));
            false
        }
    });
    // One TLS ClientHello at the public port under the given name. It never completes: what is
    // being read is whether the door passed it on.
    let knock = |name: &str| {
        Command::new("curl")
            .args([
                "--silent",
                "--show-error",
                "--max-time",
                "3",
                "--insecure",
                "--noproxy",
                "*",
                "--resolve",
            ])
            .arg(format!("{name}:{public_port}:127.0.0.1"))
            .arg(format!("https://{name}:{public_port}/"))
            .output()
            .expect("跑不起来 curl");
    };
    // What reached the site, each entry the opening bytes of one connection. Read for the name
    // inside rather than counted: the name travels in the clear in the ClientHello, which is the
    // whole premise of the guard, so each arrival can simply be asked which one it carries.
    let mut arrivals = Vec::<String>::new();
    let collect = |arrivals: &mut Vec<String>, window: Duration| {
        let deadline = std::time::Instant::now() + window;
        while std::time::Instant::now() < deadline {
            match site.accept() {
                Ok((mut stream, _)) => {
                    stream
                        .set_read_timeout(Some(Duration::from_millis(300)))
                        .ok();
                    let mut buffer = [0u8; 2048];
                    let read = stream.read(&mut buffer).unwrap_or(0);
                    arrivals.push(String::from_utf8_lossy(&buffer[..read]).into_owned());
                }
                Err(_) => thread::sleep(Duration::from_millis(20)),
            }
        }
    };

    if ready {
        // REALITY profiles `dest` on its own at startup (`XTLS/REALITY` `record_detect.go` dials
        // it once per SNI and ALPN), so the site is spoken to before anybody knocks — and those
        // connections carry the borrowed name, being the name REALITY borrows. They are drained
        // and thrown away rather than tolerated among the arrivals: left in, they answer the
        // "borrowed name still gets through" half by themselves, and this test reads green in a
        // run where no knock reached the site at all. That is not hypothetical — it is exactly
        // what the port collision above produced, and what kept it looking like a rare flake
        // rather than a test that was mostly not testing.
        //
        // Drained until the site has been quiet for a whole window, because the profiling is
        // dialled concurrently with the listener the readiness loop above is waiting on, so its
        // last connection can land after the first one.
        let mut profiling = Vec::new();
        loop {
            let before = profiling.len();
            collect(&mut profiling, Duration::from_millis(300));
            if profiling.len() == before {
                break;
            }
        }
        // Twice each, so that one connection lost to a startup race decides nothing.
        for _ in 0..2 {
            knock(BORROWED);
            collect(&mut arrivals, Duration::from_millis(600));
        }
        for _ in 0..2 {
            knock(STRANGER);
            collect(&mut arrivals, Duration::from_millis(600));
        }
    }

    // Terminated rather than killed: xray's file log is buffered, and SIGKILL loses whatever it
    // has not written — which is exactly the routing decisions this asserts on.
    let _ = Command::new("kill").arg(child.id().to_string()).status();
    let _ = child.wait();
    let log = fs::read_to_string(&error_log).unwrap_or_default();
    let _ = fs::remove_dir_all(&dir);

    assert!(ready, "xray 没有监听 REALITY 公网口");
    assert!(
        arrivals.iter().any(|hello| hello.contains(BORROWED)),
        "借用站点自己的名字一次都没到达：\n{arrivals:#?}\n{log}"
    );
    assert!(
        !arrivals.iter().any(|hello| hello.contains(STRANGER)),
        "别的名字也放进了借用站点：\n{arrivals:#?}\n{log}"
    );
    assert!(
        log.contains(&format!(
            "taking detour [{}] for [tcp:{STRANGER}:",
            xray::REALITY_GUARD_OUTBOUND_TAG
        )),
        "别的名字不是被 guard 规则挡下的：\n{log}"
    );
    assert!(
        log.contains(&format!(
            "taking detour [{}] for [tcp:{BORROWED}:",
            xray::INTERNAL_OUTBOUND_TAG
        )),
        "借用站点自己的名字没有走放行规则：\n{log}"
    );
}

/// An ingress presenting the machine's own certificate, checked against the real binary.
///
/// The certificate files are the point of the test rather than scenery: xray loads them while
/// *building* the configuration, so `-test` fails outright if the path does not resolve. That is
/// what caught the first attempt, which wrote a relative path — xray resolves those against its
/// own executable's directory rather than the working directory, so the file was looked for next
/// to the xray binary. The path is checked here as the literal string the artifact carries, and
/// the file is placed at it.
#[test]
fn a_tls_ingress_loads_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };

    // The artifact names the fleet's own directory, which this machine has no business writing
    // to — so the file goes somewhere writable and the path is swapped in the config text just
    // before xray reads it. What the artifact says is asserted separately, below. Skipping
    // instead would leave a test that passes everywhere and checks nothing.
    let dir = std::env::temp_dir().join("brocade-xray-tls");
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    let (certificate, key) = self_signed();
    fs::write(dir.join("cert.pem"), certificate).unwrap();
    fs::write(dir.join("key.pem"), key).unwrap();

    for (name, xhttp) in [
        ("tls-tcp", None),
        (
            "tls-xhttp",
            Some(Xhttp {
                path: "/probe".to_owned(),
                host: None,
                xmux: Some(XhttpXmux::with_concurrency(8)),
                tuning: None,
                mode: XhttpMode::StreamOne,
            }),
        ),
    ] {
        let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
        app.ingresses[0].wires = IngressWires::Vless(match xhttp {
            None => Transport::VlessTls(Tls {
                // Vision is legal over direct TLS, unlike over XHTTP, so this shape is the one
                // place a certificate and flow control can be asked for together.
                flow: Some("xtls-rprx-vision".to_owned()),
            }),
            Some(xhttp) => Transport::VlessTlsXhttp(TlsXhttp {
                tls: Tls {
                    flow: Some(String::new()),
                },
                xhttp,
            }),
        });
        let node = doc.nodes.iter_mut().find(|node| node.id == "hk").unwrap();
        node.certificate_name = Some("a1b2c3d4.example.net".to_owned());

        let mut diagnostics = Vec::new();
        let sys = compile_system(&doc, &mut diagnostics);
        let app_ir = compile_hops(
            compile_app(&doc, &app, &mut diagnostics),
            &sys,
            &mut diagnostics,
        );
        assert!(
            diagnostics.iter().all(|d| d.level != Level::Error),
            "{diagnostics:#?}"
        );

        let config = json::xray(&xray::build(&project_node(
            &sys,
            std::slice::from_ref(&app_ir),
            "hk",
        )));
        assert!(
            config.contains("\"security\": \"tls\"")
                && config.contains(xray::NODE_CERTIFICATE_FILE),
            "产物里没有 tls 的痕迹：\n{config}"
        );
        assert!(
            !config.contains("realitySettings"),
            "这一档不该写 REALITY 参数：\n{config}"
        );

        let path = dir.join(format!("{name}.json"));
        fs::write(
            &path,
            config
                .replace(
                    xray::NODE_CERTIFICATE_FILE,
                    &dir.join("cert.pem").display().to_string(),
                )
                .replace(
                    xray::NODE_CERTIFICATE_KEY_FILE,
                    &dir.join("key.pem").display().to_string(),
                ),
        )
        .unwrap();
        let output = Command::new(&binary)
            .args(["-test", "-c"])
            .arg(&path)
            .output()
            .expect("跑不起来 xray");
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains("Configuration OK"),
            "{name} 的产物 xray 不认：\n{stdout}\n{}\n----\n{config}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let _ = fs::remove_dir_all(&dir);
}

/// Hysteria 2's settings are spread over protocol settings, TLS, transport settings and
/// finalmask. A real-binary check keeps those four nesting levels honest.
#[test]
fn a_hysteria2_ingress_loads_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    let dir = std::env::temp_dir().join("brocade-xray-hysteria2");
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    let (certificate, key) = self_signed();
    fs::write(dir.join("cert.pem"), certificate).unwrap();
    fs::write(dir.join("key.pem"), key).unwrap();

    let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
    app.ingresses[0].wires = IngressWires::Hysteria2(Hysteria2 {
        bbr_profile: brocade_core::model::HysteriaBbrProfile::default(),
        quic: brocade_core::model::HysteriaQuic::default(),
        port: 50000,
        hop: None,
        bandwidth: HysteriaBandwidth {
            up: Some("20 mbps".to_owned()),
            down: Some("100 mbps".to_owned()),
        },
        congestion: HysteriaCongestion::Brutal,
        obfs: Some(HysteriaObfs::Salamander {
            password: "salamander-secret".to_owned(),
        }),
        masquerade: HysteriaMasquerade::Proxy {
            url: "https://cover.example.net/".to_owned(),
        },
    });
    doc.nodes
        .iter_mut()
        .find(|node| node.id == "hk")
        .unwrap()
        .certificate_name = Some("a1b2c3d4.example.net".to_owned());

    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics.iter().all(|d| d.level != Level::Error),
        "{diagnostics:#?}"
    );
    let config = json::xray(&xray::build(&project_node(
        &sys,
        std::slice::from_ref(&app_ir),
        "hk",
    )));
    let value: Value = serde_json::from_str(&config).unwrap();
    let inbound = value["inbounds"]
        .as_array()
        .unwrap()
        .iter()
        .find(|inbound| inbound["tag"] == "in:relay/i-relay:hy2")
        .expect("Hysteria 2 inbound");
    assert_eq!(inbound["protocol"], "hysteria");
    assert_eq!(
        inbound["streamSettings"]["tlsSettings"]["alpn"],
        json!(["h3"])
    );
    assert_eq!(
        inbound["streamSettings"]["finalmask"]["quicParams"]["brutalUp"],
        "20 mbps"
    );
    assert_eq!(
        inbound["streamSettings"]["finalmask"]["udp"][0]["type"],
        "salamander"
    );
    assert_eq!(
        inbound["streamSettings"]["hysteriaSettings"]["masquerade"]["url"],
        "https://cover.example.net/"
    );

    let path = dir.join("hysteria2.json");
    fs::write(
        &path,
        config
            .replace(
                xray::NODE_CERTIFICATE_FILE,
                &dir.join("cert.pem").display().to_string(),
            )
            .replace(
                xray::NODE_CERTIFICATE_KEY_FILE,
                &dir.join("key.pem").display().to_string(),
            ),
    )
    .unwrap();
    let output = Command::new(&binary)
        .args(["-test", "-c"])
        .arg(&path)
        .output()
        .expect("跑不起来 xray");
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("Configuration OK"),
        "Hysteria 2 产物 xray 不认：\n{stdout}\n{}\n----\n{config}",
        String::from_utf8_lossy(&output.stderr)
    );
    let _ = fs::remove_dir_all(&dir);
}

/// A throwaway certificate for the check above. Self-signed and expired-proof only in the sense
/// that xray never validates an inbound's own certificate — it only has to parse and pair.
fn self_signed() -> (String, String) {
    let key = rcgen::KeyPair::generate().unwrap();
    let mut params =
        rcgen::CertificateParams::new(vec!["a1b2c3d4.example.net".to_owned()]).unwrap();
    params.distinguished_name = rcgen::DistinguishedName::new();
    let certificate = params.self_signed(&key).unwrap();
    (certificate.pem(), key.serialize_pem())
}

fn free_tcp_ports(count: usize) -> Vec<u16> {
    let listeners = (0..count)
        .map(|_| TcpListener::bind((Ipv4Addr::LOCALHOST, 0)).unwrap())
        .collect::<Vec<_>>();
    listeners
        .iter()
        .map(|listener| listener.local_addr().unwrap().port())
        .collect()
}

fn fixture(
    dial: HopDial,
    security: HopWire,
) -> (
    brocade_core::ir::system::SystemIr,
    brocade_core::ir::routing::AppIr,
) {
    let (doc, app) = base_model(dial, security);
    let mut diagnostics = Vec::new();
    let sys = compile_system(&doc, &mut diagnostics);
    let app_ir = compile_hops(
        compile_app(&doc, &app, &mut diagnostics),
        &sys,
        &mut diagnostics,
    );
    assert!(
        diagnostics.iter().all(|d| d.level != Level::Error),
        "{diagnostics:#?}"
    );
    (sys, app_ir)
}

/// The uncompiled pair, so a case can reshape the steps before compiling. The reverse
/// case needs that: its two machines are not symmetric with the forward ones.
fn base_model(dial: HopDial, security: HopWire) -> (ModelSnapshot, AppView) {
    let doc = ModelSnapshot {
        revision: 1,
        overlay_cidr: Ipv4Net::new(Ipv4Addr::new(10, 66, 0, 0), 16).unwrap(),
        settings: Default::default(),
        nodes: vec![node("hk", [10, 66, 0, 1]), node("sg", [10, 66, 0, 2])],
        node_egress_dns: Vec::new(),
        users: vec![User {
            tenant: "platform".to_owned(),
            id: "alice".to_owned(),
            uuid: "6f9d1a8e-2b3c-4d5e-8f70-1a2b3c4d5e6f".to_owned(),
        }],
        external_outbounds: Vec::new(),
        apps: Vec::new(),
    };

    let app = AppView {
        id: "relay".to_owned(),
        label: "中转".to_owned(),
        chains: vec![Chain {
            id: "c-relay".to_owned(),
            tenant: "platform".to_owned(),
            name: "中转链".to_owned(),
            subscription_country: None,
        }],
        ingresses: vec![Ingress {
            id: "i-relay".to_owned(),
            chain: "c-relay".to_owned(),
            node: "hk".to_owned(),
            bind: IpAddr::from(Ipv4Addr::UNSPECIFIED),
            port: 443,
            front: None,
            projection: Default::default(),
            guard: brocade_core::model::IngressGuard::OPEN,
            identity: brocade_core::model::IngressIdentity {
                private_key: INGRESS_PRIVATE.to_owned(),
                public_key: INGRESS_PUBLIC.to_owned(),
                short_ids: vec!["abcdef0123456789".to_owned()],
            },
            wires: IngressWires::Vless(Transport::VlessReality(
                brocade_core::model::RealitySettings {
                    dest: "apps.apple.com:443".to_owned(),
                    server_names: vec!["apps.apple.com".to_owned()],
                    fingerprint: "chrome".to_owned(),
                    flow: None,
                    fallback_mode: Default::default(),
                    fallback_guard: true,
                    fallback_limits: Default::default(),
                },
            )),
        }],
        fronts: Vec::new(),
        steps: vec![
            Step {
                chain: "c-relay".to_owned(),
                node: "hk".to_owned(),
                accept: None,
                hop_in: None,
                rules: vec![Rule {
                    dest_match: DestMatch::Any,
                    action: Action::Forward {
                        to: "sg".to_owned(),
                        dial,
                        pool: HopPool::None,
                    },
                }],
            },
            Step {
                chain: "c-relay".to_owned(),
                node: "sg".to_owned(),
                accept: Some(Accept {
                    uuid: "2c3b4d5e-6f70-4a8b-9c0d-1e2f3a4b5c6d".to_owned(),
                    label: "c-relay@sg".to_owned(),
                }),
                hop_in: Some(HopIn {
                    port: 20000,
                    security,
                }),
                rules: vec![Rule {
                    dest_match: DestMatch::Any,
                    action: Action::Egress { send_through: None },
                }],
            },
        ],
        grants: Vec::new(),
    };

    (doc, app)
}

fn node(id: &str, overlay: [u8; 4]) -> Node {
    Node {
        mtu: None,
        connection: Default::default(),
        id: id.to_owned(),
        tenant: "platform".to_owned(),
        name: id.to_owned(),
        public_ipv4: Some(format!("{id}.example.net")),
        public_ipv6: None,
        public_ipv4_nat: false,
        public_ipv6_nat: false,
        overlay_addr: Ipv4Addr::from(overlay),
        certificate_name: None,
        wireguard: WireGuardKeys {
            private_key: "QG4l1cVXHNVPQxL0FKBTaFAsuGSKLFB39JYFhTOEXFo=".to_owned(),
            public_key: "T3JqRDF3ZmFrZXB1YmtleWZha2VwdWJrZXlmYWtlcHViaz0=".to_owned(),
            listen_port: 51820,
            transport: Default::default(),
        },
        api_port: Some(10085),
        overlay: true,
        egress_allowed: true,
        dns: Dns::System,
        domain_strategy: DomainStrategy::default(),
        retired: false,
    }
}

/// The liveness section must actually send probes, not merely load as configuration.
///
/// xray passes unrecognized top-level keys silently (insert a `thisKeyDoesNotExist` and it
/// still reports Configuration OK), so `-test` proves nothing here. The only thing that
/// counts is `app/observatory/burst: checking <tag>` appearing in the log once it runs.
///
/// So this test watches behavior rather than shape: with `burstObservatory` configured but
/// no rule referencing the balancer, the config passes just the same while not one probe is
/// ever sent.
#[test]
fn the_hop_health_observatory_actually_probes() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };

    let (sys, app_ir) = fixture(HopDial::Overlay, HopWire::None);
    let config = json::xray(&xray::build(&project_node(
        &sys,
        std::slice::from_ref(&app_ir),
        "hk",
    )));
    assert!(
        config.contains("burstObservatory"),
        "hk 有转发出口，该出判活段：{config}"
    );

    let dir = std::env::temp_dir().join("brocade-hop-health");
    fs::create_dir_all(&dir).unwrap();
    let path = dir.join("xray.json");
    // The log has to go to debug for the observatory to be visible; the artifact itself
    // uses warning.
    fs::write(
        &path,
        config
            // The log has to go to debug for the observatory to be visible; the artifact
            // itself uses warning.
            .replace("\"loglevel\": \"warning\"", "\"loglevel\": \"debug\"")
            // The ingress is 443 in the fixture, which non-root cannot bind, so xray exits
            // before the observatory starts. Liveness has nothing to do with the ingress
            // port, and a high port changes nothing this test sets out to prove.
            .replace("\"port\": 443", "\"port\": 18443"),
    )
    .unwrap();

    let mut child = Command::new(&binary)
        .args(["run", "-c"])
        .arg(&path)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("跑不起来 xray");
    std::thread::sleep(std::time::Duration::from_secs(4));
    let _ = child.kill();
    let output = child.wait_with_output().unwrap();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let _ = fs::remove_dir_all(&dir);

    assert!(
        log.contains("app/observatory/burst: checking"),
        "observatory 没有真的开始探测。只配 burstObservatory 是不够的，\
         必须有一条路由规则引用 balancer 才会实例化：\n{log}"
    );
}

/// The tag the deployment template pins is the release these tests validate against.
///
/// They are one decision seen from two sides: `console.env.example` says which xray every new
/// machine installs, and `.tools/xray` is the build every assertion in this file is checked
/// against. Letting them drift produces two failures that both pass CI — pinning a tag nothing
/// has ever run, or validating a build nobody installs — and neither shows up until a machine in
/// the field cannot carry traffic.
///
/// The template rather than the database or the environment, because the template is the only
/// copy under version control: the other two are per-deployment, and a test cannot see them.
///
/// Skipped without the binary, like the rest of this file.
#[test]
fn the_pinned_tag_matches_the_binary_these_tests_use() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };
    let template = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("workspace root")
        .join("console.env.example");
    let text = fs::read_to_string(&template).expect("读得到 console.env.example");
    let pinned = text
        .lines()
        .find_map(|line| line.strip_prefix("BROCADE_XRAY_VERSION="))
        .map(str::trim)
        .expect("console.env.example 里要有 BROCADE_XRAY_VERSION");

    let output = Command::new(&binary)
        .arg("version")
        .output()
        .expect("跑得了 xray version");
    let reported = String::from_utf8_lossy(&output.stdout);
    // `Xray 26.4.25 (...)` against a tag written the way the release page writes it, with `v`.
    let expected = format!("Xray {} ", pinned.trim_start_matches('v'));
    assert!(
        reported.contains(&expected),
        "console.env.example 钉的是 {pinned}，而 {} 报的是：{}",
        binary.display(),
        reported.lines().next().unwrap_or("")
    );
}

/// The point of naming every rule: a compiled table has to be installable into a running
/// xray, so that a routing change stops costing every connection on the machine.
///
/// The procedure is fixed, and both halves of it are load-bearing. `adrules` **replaces**
/// the table unless `-append` is given, and a replacement destroys the balancers — after
/// which the liveness balancer cannot be rebuilt at all (`app/router: duplicate balancer
/// tag` on the way back, and an unreferenced one is never reclaimed), so hop liveness
/// would be silently dead for the rest of the process's life. Appending first also means
/// the old rules, still ahead of the new ones, keep deciding until the moment they are
/// removed, so no request is ever routed by a half-installed table.
///
/// That leaves one requirement on the compiler, which is what this test really guards:
/// the two generations must not share a single `ruleTag`. Both tables are present at
/// once during the append and xray rejects a duplicate — atomically, so a collision does
/// not half-apply, it leaves the machine on its old routing while reporting a failure.
#[test]
fn a_compiled_rule_table_swaps_into_a_running_xray() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };

    // Two tables from the same machine, differing only in its rules: the second splits
    // the catch-all in two by matching a domain ahead of it. Same outbounds, same
    // inbounds, same balancer — so what the swap exercises is the rule table alone.
    let compile = |extra: Option<DestMatch>| {
        let (mut doc, mut app) = base_model(HopDial::Overlay, HopWire::None);
        doc.settings = Default::default();
        if let Some(dest_match) = extra {
            let step = app
                .steps
                .iter_mut()
                .find(|step| step.node == "hk")
                .expect("hk 有一步");
            let action = step.rules[0].action.clone();
            step.rules.insert(0, Rule { dest_match, action });
        }
        let mut diagnostics = Vec::new();
        let sys = compile_system(&doc, &mut diagnostics);
        let app_ir = compile_hops(
            compile_app(&doc, &app, &mut diagnostics),
            &sys,
            &mut diagnostics,
        );
        assert!(
            diagnostics.iter().all(|d| d.level != Level::Error),
            "{diagnostics:#?}"
        );
        json::xray(&xray::build(&project_node(
            &sys,
            std::slice::from_ref(&app_ir),
            "hk",
        )))
    };

    let before = compile(None);
    let after = compile(Some(DestMatch::DomainSuffix(
        vec!["example.com".to_owned()],
    )));

    let rules_of = |config: &str| -> Vec<Value> {
        serde_json::from_str::<Value>(config).unwrap()["routing"]["rules"]
            .as_array()
            .unwrap()
            .clone()
    };
    let tags_of = |config: &str| -> Vec<String> {
        rules_of(config)
            .iter()
            .map(|rule| {
                rule["ruleTag"]
                    .as_str()
                    .expect("每条规则都有名字")
                    .to_owned()
            })
            .collect()
    };

    let (old_tags, new_tags) = (tags_of(&before), tags_of(&after));
    for tag in &new_tags {
        assert!(
            !old_tags.contains(tag),
            "{tag} 两代都有：追加时 xray 会因 duplicate ruleTag 整批拒绝，机器留在旧路由上",
        );
    }

    let dir = std::env::temp_dir().join("brocade-rule-swap");
    fs::create_dir_all(&dir).unwrap();
    let api = "127.0.0.1:19187";
    // The fixture binds the ingress on 443 and the hop inbounds on overlay addresses that
    // do not exist here; neither has any bearing on the rule table.
    let runnable = before
        .replace("\"port\": 443", "\"port\": 19188")
        .replace("\"port\": 10085", "\"port\": 19187")
        .replace("\"listen\": \"10.66.0.1\"", "\"listen\": \"127.0.0.1\"");
    let path = dir.join("xray.json");
    fs::write(&path, &runnable).unwrap();

    let mut child = Command::new(&binary)
        .args(["run", "-c"])
        .arg(&path)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("跑不起来 xray");
    // `--server` goes immediately after the verb, never at the end: Go's flag parser stops
    // at the first non-flag argument, so a `--server` written after a file name is taken
    // for another file and the call quietly dials the default 127.0.0.1:8080 instead.
    let api_call = |args: &[&str]| -> (bool, String) {
        let (verb, rest) = args.split_first().expect("至少要有子命令");
        let output = Command::new(&binary)
            .arg("api")
            .arg(verb)
            .arg(format!("--server={api}"))
            .args(rest)
            .output()
            .expect("调不动 xray api");
        (
            output.status.success(),
            format!(
                "{}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            ),
        )
    };
    // The api listener is the readiness signal; without it every call below races startup.
    let mut ready = false;
    for _ in 0..80 {
        if api_call(&["lsrules"]).0 {
            ready = true;
            break;
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
    let outcome = (|| -> Result<(), String> {
        if !ready {
            return Err("xray 的 api 口一直没起来".to_owned());
        }

        let installed = |label: &str| -> Result<Vec<String>, String> {
            let (ok, text) = api_call(&["lsrules"]);
            if !ok {
                return Err(format!("{label}: lsrules 失败 {text}"));
            }
            Ok(serde_json::from_str::<Value>(&text)
                .map_err(|error| format!("{label}: {error} / {text}"))?["rules"]
                .as_array()
                .ok_or_else(|| format!("{label}: 没有 rules"))?
                .iter()
                .filter_map(|rule| rule["ruleTag"].as_str().map(str::to_owned))
                .collect())
        };

        // Every compiled rule is addressable. An unnamed one is reported as `{}` and
        // `rmrules` cannot reach it, which would strand the whole table.
        let live = installed("装载后")?;
        if live != old_tags {
            return Err(format!(
                "跑起来的规则名和编译出的对不上：{live:?} vs {old_tags:?}"
            ));
        }

        // The balancer is declared once, at startup, and must be referenced but never
        // re-declared: sending `routing.balancers` again is rejected as a duplicate.
        let payload = dir.join("next.json");
        fs::write(
            &payload,
            serde_json::to_string(&json!({ "routing": { "rules": rules_of(&after) } })).unwrap(),
        )
        .map_err(|error| error.to_string())?;

        let (ok, text) = api_call(&["adrules", "-append", payload.to_str().unwrap()]);
        if !ok {
            return Err(format!("追加新表失败：{text}"));
        }
        let both = installed("追加后")?;
        if both.len() != old_tags.len() + new_tags.len() {
            return Err(format!("追加后两代应当并存，实际 {both:?}"));
        }

        let mut remove = vec!["rmrules"];
        remove.extend(old_tags.iter().map(String::as_str));
        let (ok, text) = api_call(&remove);
        if !ok {
            return Err(format!("撤旧表失败：{text}"));
        }
        let live = installed("撤旧后")?;
        if live != new_tags {
            return Err(format!("换表后剩下的不是新表：{live:?} vs {new_tags:?}"));
        }

        // What a naive replace would have destroyed. Hop liveness rides on this balancer,
        // and losing it produces no error anywhere — the probes simply stop.
        let (ok, text) = api_call(&["bi", HOP_HEALTH_BALANCER_TAG]);
        if !ok {
            return Err(format!("换表后判活 balancer 没了：{text}"));
        }
        Ok(())
    })();

    let _ = child.kill();
    let output = child.wait_with_output().unwrap();
    if let Err(reason) = outcome {
        panic!(
            "{reason}\nxray 日志：\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
}

/// Connection pooling, against a real xray.
///
/// The `mux` block is written onto the outbound, and there is no unit test that can prove
/// xray takes it — which is this file's whole reason for existing. Two gaps in particular:
///
/// The Shadowsocks branch of `forward_outbound` emits `mux` exactly as the VLESS branch
/// does, and no golden covers that pairing; both compiled artifacts carrying a `mux` block
/// today hang it off a VLESS outbound. A protocol that rejected it would fail at startup on
/// the relays alone, which is the half of the fleet whose configs nobody reads.
///
/// And `xray -test` cannot stand in for the range check. Measured on 26.4.25, a
/// `concurrency` of 0, 129 or 200 all report `Configuration OK` — xray reads 0 as 8 and
/// clamps above 128 at runtime, silently. That is why `validate` refuses those values
/// instead of passing them on, and why a green `-test` says nothing about them.
#[test]
fn pooled_hops_load_in_the_real_binary() {
    let Some(binary) = xray_binary() else {
        eprintln!("跳过：没找到 xray 二进制（设 BROCADE_XRAY_BIN 或放到 .tools/xray）");
        return;
    };

    const SERVER_PSK: &str = "SGVsbG9Ccm9jYWRlS2V5MDE=";
    const USER_PSK: &str = "QnJvY2FkZVVzZXJLZXkwMDA9";

    let cases = [
        ("vless-pool", HopWire::None, HopPool::Pool),
        (
            "vless-merge",
            HopWire::None,
            HopPool::Merge(HopPool::MERGE_MAX),
        ),
        (
            "shadowsocks-pool",
            HopWire::Shadowsocks2022 {
                server_psk: SERVER_PSK.to_owned(),
                user_psk: USER_PSK.to_owned(),
            },
            HopPool::Pool,
        ),
        (
            "shadowsocks-merge",
            HopWire::Shadowsocks2022 {
                server_psk: SERVER_PSK.to_owned(),
                user_psk: USER_PSK.to_owned(),
            },
            HopPool::Merge(HopPool::MERGE_MIN),
        ),
    ];

    for (name, security, pool) in cases {
        let (doc, mut app) = base_model(HopDial::Overlay, security);
        let step = app
            .steps
            .iter_mut()
            .find(|step| step.node == "hk")
            .expect("hk 是拨号的一端");
        for rule in &mut step.rules {
            if let Action::Forward { pool: slot, .. } = &mut rule.action {
                *slot = pool;
            }
        }

        let mut diagnostics = Vec::new();
        let sys = compile_system(&doc, &mut diagnostics);
        let app_ir = compile_hops(
            compile_app(&doc, &app, &mut diagnostics),
            &sys,
            &mut diagnostics,
        );
        assert!(
            diagnostics.iter().all(|d| d.level != Level::Error),
            "{name}: {diagnostics:#?}"
        );

        // hk dials, so hk is where the pool lands; sg is checked too because the receiving
        // side has to keep loading with a pooled peer on the other end.
        for node_id in ["hk", "sg"] {
            let config = json::xray(&xray::build(&project_node(
                &sys,
                std::slice::from_ref(&app_ir),
                node_id,
            )));
            if node_id == "hk" {
                let value: Value = serde_json::from_str(&config).unwrap();
                let mux = value["outbounds"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .find_map(|outbound| outbound.get("mux"))
                    .unwrap_or_else(|| panic!("{name}: 拨号端该带 mux：{config}"));
                assert_eq!(mux["enabled"], json!(true), "{name}");
                assert_eq!(
                    mux["concurrency"],
                    json!(match pool {
                        HopPool::Pool => 1,
                        HopPool::Merge(n) => n,
                        HopPool::None => unreachable!("用例里没有 None"),
                    }),
                    "{name}"
                );
            }

            let path =
                std::env::temp_dir().join(format!("brocade-xray-pool-{name}-{node_id}.json"));
            fs::write(&path, &config).unwrap();
            let output = Command::new(&binary)
                .args(["-test", "-c"])
                .arg(&path)
                .output()
                .expect("跑不起来 xray");
            let stdout = String::from_utf8_lossy(&output.stdout);
            assert!(
                stdout.contains("Configuration OK"),
                "{name}/{node_id} 的产物 xray 不认：\n{stdout}\n{}\n----\n{config}",
                String::from_utf8_lossy(&output.stderr),
            );
            let _ = fs::remove_file(&path);
        }
    }
}
