// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/vless/account.proto

package vless

import (
	proxyman "github.com/xtls/xray-core/app/proxyman"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReverseHealthTuning struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProbeJitterPercent     uint32                 `protobuf:"varint,1,opt,name=probe_jitter_percent,json=probeJitterPercent,proto3" json:"probe_jitter_percent,omitempty"`
	RecoverySuccesses      uint32                 `protobuf:"varint,2,opt,name=recovery_successes,json=recoverySuccesses,proto3" json:"recovery_successes,omitempty"`
	SpareWorkers           uint32                 `protobuf:"varint,3,opt,name=spare_workers,json=spareWorkers,proto3" json:"spare_workers,omitempty"`
	MaxHealthyWorkers      uint32                 `protobuf:"varint,4,opt,name=max_healthy_workers,json=maxHealthyWorkers,proto3" json:"max_healthy_workers,omitempty"`
	MaxSessionsPerWorker   uint32                 `protobuf:"varint,5,opt,name=max_sessions_per_worker,json=maxSessionsPerWorker,proto3" json:"max_sessions_per_worker,omitempty"`
	ReconnectBackoffBaseMs uint32                 `protobuf:"varint,6,opt,name=reconnect_backoff_base_ms,json=reconnectBackoffBaseMs,proto3" json:"reconnect_backoff_base_ms,omitempty"`
	ReconnectStableResetMs uint32                 `protobuf:"varint,7,opt,name=reconnect_stable_reset_ms,json=reconnectStableResetMs,proto3" json:"reconnect_stable_reset_ms,omitempty"`
	CanaryIntervalMs       uint32                 `protobuf:"varint,8,opt,name=canary_interval_ms,json=canaryIntervalMs,proto3" json:"canary_interval_ms,omitempty"`
	CanaryTimeoutMs        uint32                 `protobuf:"varint,9,opt,name=canary_timeout_ms,json=canaryTimeoutMs,proto3" json:"canary_timeout_ms,omitempty"`
	CanarySuccesses        uint32                 `protobuf:"varint,10,opt,name=canary_successes,json=canarySuccesses,proto3" json:"canary_successes,omitempty"`
	CanaryStableWindowMs   uint32                 `protobuf:"varint,11,opt,name=canary_stable_window_ms,json=canaryStableWindowMs,proto3" json:"canary_stable_window_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReverseHealthTuning) Reset() {
	*x = ReverseHealthTuning{}
	mi := &file_proxy_vless_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseHealthTuning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseHealthTuning) ProtoMessage() {}

func (x *ReverseHealthTuning) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_vless_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseHealthTuning.ProtoReflect.Descriptor instead.
func (*ReverseHealthTuning) Descriptor() ([]byte, []int) {
	return file_proxy_vless_account_proto_rawDescGZIP(), []int{0}
}

func (x *ReverseHealthTuning) GetProbeJitterPercent() uint32 {
	if x != nil {
		return x.ProbeJitterPercent
	}
	return 0
}

func (x *ReverseHealthTuning) GetRecoverySuccesses() uint32 {
	if x != nil {
		return x.RecoverySuccesses
	}
	return 0
}

func (x *ReverseHealthTuning) GetSpareWorkers() uint32 {
	if x != nil {
		return x.SpareWorkers
	}
	return 0
}

func (x *ReverseHealthTuning) GetMaxHealthyWorkers() uint32 {
	if x != nil {
		return x.MaxHealthyWorkers
	}
	return 0
}

func (x *ReverseHealthTuning) GetMaxSessionsPerWorker() uint32 {
	if x != nil {
		return x.MaxSessionsPerWorker
	}
	return 0
}

func (x *ReverseHealthTuning) GetReconnectBackoffBaseMs() uint32 {
	if x != nil {
		return x.ReconnectBackoffBaseMs
	}
	return 0
}

func (x *ReverseHealthTuning) GetReconnectStableResetMs() uint32 {
	if x != nil {
		return x.ReconnectStableResetMs
	}
	return 0
}

func (x *ReverseHealthTuning) GetCanaryIntervalMs() uint32 {
	if x != nil {
		return x.CanaryIntervalMs
	}
	return 0
}

func (x *ReverseHealthTuning) GetCanaryTimeoutMs() uint32 {
	if x != nil {
		return x.CanaryTimeoutMs
	}
	return 0
}

func (x *ReverseHealthTuning) GetCanarySuccesses() uint32 {
	if x != nil {
		return x.CanarySuccesses
	}
	return 0
}

func (x *ReverseHealthTuning) GetCanaryStableWindowMs() uint32 {
	if x != nil {
		return x.CanaryStableWindowMs
	}
	return 0
}

type ReverseHealth struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ProbeIntervalMs         uint32                 `protobuf:"varint,1,opt,name=probe_interval_ms,json=probeIntervalMs,proto3" json:"probe_interval_ms,omitempty"`
	ProbeTimeoutMs          uint32                 `protobuf:"varint,2,opt,name=probe_timeout_ms,json=probeTimeoutMs,proto3" json:"probe_timeout_ms,omitempty"`
	ConfirmTimeoutMs        uint32                 `protobuf:"varint,3,opt,name=confirm_timeout_ms,json=confirmTimeoutMs,proto3" json:"confirm_timeout_ms,omitempty"`
	HealthLeaseMs           uint32                 `protobuf:"varint,4,opt,name=health_lease_ms,json=healthLeaseMs,proto3" json:"health_lease_ms,omitempty"`
	MinHealthyWorkers       uint32                 `protobuf:"varint,5,opt,name=min_healthy_workers,json=minHealthyWorkers,proto3" json:"min_healthy_workers,omitempty"`
	MaxIdleReadyWorkers     uint32                 `protobuf:"varint,6,opt,name=max_idle_ready_workers,json=maxIdleReadyWorkers,proto3" json:"max_idle_ready_workers,omitempty"`
	MaxParallelDialsPerPair uint32                 `protobuf:"varint,7,opt,name=max_parallel_dials_per_pair,json=maxParallelDialsPerPair,proto3" json:"max_parallel_dials_per_pair,omitempty"`
	DialReadyTimeoutMs      uint32                 `protobuf:"varint,8,opt,name=dial_ready_timeout_ms,json=dialReadyTimeoutMs,proto3" json:"dial_ready_timeout_ms,omitempty"`
	ReconnectBackoffCapMs   uint32                 `protobuf:"varint,9,opt,name=reconnect_backoff_cap_ms,json=reconnectBackoffCapMs,proto3" json:"reconnect_backoff_cap_ms,omitempty"`
	Tuning                  *ReverseHealthTuning   `protobuf:"bytes,10,opt,name=tuning,proto3" json:"tuning,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReverseHealth) Reset() {
	*x = ReverseHealth{}
	mi := &file_proxy_vless_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseHealth) ProtoMessage() {}

func (x *ReverseHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_vless_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseHealth.ProtoReflect.Descriptor instead.
func (*ReverseHealth) Descriptor() ([]byte, []int) {
	return file_proxy_vless_account_proto_rawDescGZIP(), []int{1}
}

func (x *ReverseHealth) GetProbeIntervalMs() uint32 {
	if x != nil {
		return x.ProbeIntervalMs
	}
	return 0
}

func (x *ReverseHealth) GetProbeTimeoutMs() uint32 {
	if x != nil {
		return x.ProbeTimeoutMs
	}
	return 0
}

func (x *ReverseHealth) GetConfirmTimeoutMs() uint32 {
	if x != nil {
		return x.ConfirmTimeoutMs
	}
	return 0
}

func (x *ReverseHealth) GetHealthLeaseMs() uint32 {
	if x != nil {
		return x.HealthLeaseMs
	}
	return 0
}

func (x *ReverseHealth) GetMinHealthyWorkers() uint32 {
	if x != nil {
		return x.MinHealthyWorkers
	}
	return 0
}

func (x *ReverseHealth) GetMaxIdleReadyWorkers() uint32 {
	if x != nil {
		return x.MaxIdleReadyWorkers
	}
	return 0
}

func (x *ReverseHealth) GetMaxParallelDialsPerPair() uint32 {
	if x != nil {
		return x.MaxParallelDialsPerPair
	}
	return 0
}

func (x *ReverseHealth) GetDialReadyTimeoutMs() uint32 {
	if x != nil {
		return x.DialReadyTimeoutMs
	}
	return 0
}

func (x *ReverseHealth) GetReconnectBackoffCapMs() uint32 {
	if x != nil {
		return x.ReconnectBackoffCapMs
	}
	return 0
}

func (x *ReverseHealth) GetTuning() *ReverseHealthTuning {
	if x != nil {
		return x.Tuning
	}
	return nil
}

type Reverse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tag           string                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Sniffing      *proxyman.SniffingConfig `protobuf:"bytes,2,opt,name=sniffing,proto3" json:"sniffing,omitempty"`
	Health        *ReverseHealth           `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	CanaryUrl     string                   `protobuf:"bytes,4,opt,name=canary_url,json=canaryUrl,proto3" json:"canary_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reverse) Reset() {
	*x = Reverse{}
	mi := &file_proxy_vless_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reverse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reverse) ProtoMessage() {}

func (x *Reverse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_vless_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reverse.ProtoReflect.Descriptor instead.
func (*Reverse) Descriptor() ([]byte, []int) {
	return file_proxy_vless_account_proto_rawDescGZIP(), []int{2}
}

func (x *Reverse) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Reverse) GetSniffing() *proxyman.SniffingConfig {
	if x != nil {
		return x.Sniffing
	}
	return nil
}

func (x *Reverse) GetHealth() *ReverseHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *Reverse) GetCanaryUrl() string {
	if x != nil {
		return x.CanaryUrl
	}
	return ""
}

type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Flow settings. May be "xtls-rprx-vision".
	Flow          string   `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	Encryption    string   `protobuf:"bytes,3,opt,name=encryption,proto3" json:"encryption,omitempty"`
	XorMode       uint32   `protobuf:"varint,4,opt,name=xorMode,proto3" json:"xorMode,omitempty"`
	Seconds       uint32   `protobuf:"varint,5,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Padding       string   `protobuf:"bytes,6,opt,name=padding,proto3" json:"padding,omitempty"`
	Reverse       *Reverse `protobuf:"bytes,7,opt,name=reverse,proto3" json:"reverse,omitempty"`
	Testpre       uint32   `protobuf:"varint,8,opt,name=testpre,proto3" json:"testpre,omitempty"`
	Testseed      []uint32 `protobuf:"varint,9,rep,packed,name=testseed,proto3" json:"testseed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_vless_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_vless_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_vless_account_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *Account) GetEncryption() string {
	if x != nil {
		return x.Encryption
	}
	return ""
}

func (x *Account) GetXorMode() uint32 {
	if x != nil {
		return x.XorMode
	}
	return 0
}

func (x *Account) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Account) GetPadding() string {
	if x != nil {
		return x.Padding
	}
	return ""
}

func (x *Account) GetReverse() *Reverse {
	if x != nil {
		return x.Reverse
	}
	return nil
}

func (x *Account) GetTestpre() uint32 {
	if x != nil {
		return x.Testpre
	}
	return 0
}

func (x *Account) GetTestseed() []uint32 {
	if x != nil {
		return x.Testseed
	}
	return nil
}

var File_proxy_vless_account_proto protoreflect.FileDescriptor

const file_proxy_vless_account_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/vless/account.proto\x12\x10xray.proxy.vless\x1a\x19app/proxyman/config.proto\"\xb4\x04\n" +
	"\x13ReverseHealthTuning\x120\n" +
	"\x14probe_jitter_percent\x18\x01 \x01(\rR\x12probeJitterPercent\x12-\n" +
	"\x12recovery_successes\x18\x02 \x01(\rR\x11recoverySuccesses\x12#\n" +
	"\rspare_workers\x18\x03 \x01(\rR\fspareWorkers\x12.\n" +
	"\x13max_healthy_workers\x18\x04 \x01(\rR\x11maxHealthyWorkers\x125\n" +
	"\x17max_sessions_per_worker\x18\x05 \x01(\rR\x14maxSessionsPerWorker\x129\n" +
	"\x19reconnect_backoff_base_ms\x18\x06 \x01(\rR\x16reconnectBackoffBaseMs\x129\n" +
	"\x19reconnect_stable_reset_ms\x18\a \x01(\rR\x16reconnectStableResetMs\x12,\n" +
	"\x12canary_interval_ms\x18\b \x01(\rR\x10canaryIntervalMs\x12*\n" +
	"\x11canary_timeout_ms\x18\t \x01(\rR\x0fcanaryTimeoutMs\x12)\n" +
	"\x10canary_successes\x18\n" +
	" \x01(\rR\x0fcanarySuccesses\x125\n" +
	"\x17canary_stable_window_ms\x18\v \x01(\rR\x14canaryStableWindowMs\"\x89\x04\n" +
	"\rReverseHealth\x12*\n" +
	"\x11probe_interval_ms\x18\x01 \x01(\rR\x0fprobeIntervalMs\x12(\n" +
	"\x10probe_timeout_ms\x18\x02 \x01(\rR\x0eprobeTimeoutMs\x12,\n" +
	"\x12confirm_timeout_ms\x18\x03 \x01(\rR\x10confirmTimeoutMs\x12&\n" +
	"\x0fhealth_lease_ms\x18\x04 \x01(\rR\rhealthLeaseMs\x12.\n" +
	"\x13min_healthy_workers\x18\x05 \x01(\rR\x11minHealthyWorkers\x123\n" +
	"\x16max_idle_ready_workers\x18\x06 \x01(\rR\x13maxIdleReadyWorkers\x12<\n" +
	"\x1bmax_parallel_dials_per_pair\x18\a \x01(\rR\x17maxParallelDialsPerPair\x121\n" +
	"\x15dial_ready_timeout_ms\x18\b \x01(\rR\x12dialReadyTimeoutMs\x127\n" +
	"\x18reconnect_backoff_cap_ms\x18\t \x01(\rR\x15reconnectBackoffCapMs\x12=\n" +
	"\x06tuning\x18\n" +
	" \x01(\v2%.xray.proxy.vless.ReverseHealthTuningR\x06tuning\"\xb2\x01\n" +
	"\aReverse\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12=\n" +
	"\bsniffing\x18\x02 \x01(\v2!.xray.app.proxyman.SniffingConfigR\bsniffing\x127\n" +
	"\x06health\x18\x03 \x01(\v2\x1f.xray.proxy.vless.ReverseHealthR\x06health\x12\x1d\n" +
	"\n" +
	"canary_url\x18\x04 \x01(\tR\tcanaryUrl\"\x86\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\tR\x04flow\x12\x1e\n" +
	"\n" +
	"encryption\x18\x03 \x01(\tR\n" +
	"encryption\x12\x18\n" +
	"\axorMode\x18\x04 \x01(\rR\axorMode\x12\x18\n" +
	"\aseconds\x18\x05 \x01(\rR\aseconds\x12\x18\n" +
	"\apadding\x18\x06 \x01(\tR\apadding\x123\n" +
	"\areverse\x18\a \x01(\v2\x19.xray.proxy.vless.ReverseR\areverse\x12\x18\n" +
	"\atestpre\x18\b \x01(\rR\atestpre\x12\x1a\n" +
	"\btestseed\x18\t \x03(\rR\btestseedBR\n" +
	"\x14com.xray.proxy.vlessP\x01Z%github.com/xtls/xray-core/proxy/vless\xaa\x02\x10Xray.Proxy.Vlessb\x06proto3"

var (
	file_proxy_vless_account_proto_rawDescOnce sync.Once
	file_proxy_vless_account_proto_rawDescData []byte
)

func file_proxy_vless_account_proto_rawDescGZIP() []byte {
	file_proxy_vless_account_proto_rawDescOnce.Do(func() {
		file_proxy_vless_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_vless_account_proto_rawDesc), len(file_proxy_vless_account_proto_rawDesc)))
	})
	return file_proxy_vless_account_proto_rawDescData
}

var file_proxy_vless_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_vless_account_proto_goTypes = []any{
	(*ReverseHealthTuning)(nil),     // 0: xray.proxy.vless.ReverseHealthTuning
	(*ReverseHealth)(nil),           // 1: xray.proxy.vless.ReverseHealth
	(*Reverse)(nil),                 // 2: xray.proxy.vless.Reverse
	(*Account)(nil),                 // 3: xray.proxy.vless.Account
	(*proxyman.SniffingConfig)(nil), // 4: xray.app.proxyman.SniffingConfig
}
var file_proxy_vless_account_proto_depIdxs = []int32{
	0, // 0: xray.proxy.vless.ReverseHealth.tuning:type_name -> xray.proxy.vless.ReverseHealthTuning
	4, // 1: xray.proxy.vless.Reverse.sniffing:type_name -> xray.app.proxyman.SniffingConfig
	1, // 2: xray.proxy.vless.Reverse.health:type_name -> xray.proxy.vless.ReverseHealth
	2, // 3: xray.proxy.vless.Account.reverse:type_name -> xray.proxy.vless.Reverse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proxy_vless_account_proto_init() }
func file_proxy_vless_account_proto_init() {
	if File_proxy_vless_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_vless_account_proto_rawDesc), len(file_proxy_vless_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_vless_account_proto_goTypes,
		DependencyIndexes: file_proxy_vless_account_proto_depIdxs,
		MessageInfos:      file_proxy_vless_account_proto_msgTypes,
	}.Build()
	File_proxy_vless_account_proto = out.File
	file_proxy_vless_account_proto_goTypes = nil
	file_proxy_vless_account_proto_depIdxs = nil
}
